### ISSUE TITLE
No Polish language in Retroarch

### ISSUE THREAD

**Issue by kashkash18** [OnionUI/Onion#1030]
Please add Polish language to Retroarch.

**Comment by tGecko** [comment]
It's there - In RetroArch, go to Settings -> User -> Language and select Polish

**Comment by tGecko** [comment]
In fact, all [these languages](https://github.com/OnionUI/RetroArch/blob/ef98978914273fe0d9cafae300293e9293c3cd0d/menu/drivers/rgui.c#L1545) don't work:
```c
      case RETRO_LANGUAGE_ESPERANTO:
      case RETRO_LANGUAGE_POLISH:
      case RETRO_LANGUAGE_TURKISH:
      case RETRO_LANGUAGE_SLOVAK:
      case RETRO_LANGUAGE_CZECH:
      case RETRO_LANGUAGE_HUNGARIAN:
```

**Comment by tGecko** [comment]
Can you try this please:
Extract the files in this zip and move the two included files to your SD into the folder
`\RetroArch\.retroarch\assets\rgui\font\`
[font.zip](https://github.com/OnionUI/Onion/files/12105237/font.zip)
