### ISSUE TITLE
Chinese in retroarch is not displayed

### ISSUE THREAD

**Issue by xiaosagemisery** [OnionUI/Onion#1031]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0-RC

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

When I want to choose the cheat when playing game, since the Chinese can be displayed in retroarch, it is impossible for me to find the related cheat file.

### Steps to Reproduce

The english characters can be displayed but Chinese ones are ignored.

### Provide any additional context or information that may help us investigate your issue

Is it possible to fix this?

**Comment by tGecko** [comment]
This is an issue in RetroArch itself, not in Onion. I suggest you submit it [here](https://github.com/libretro/RetroArch/issues)
As you can see in the screenshot, it doesn't work on the desktop version of RetroArch either.

![image](https://github.com/OnionUI/Onion/assets/6023076/c9103104-87e4-42d0-b8ac-5c2d0f39e8c6)

As a workaround, I suggest you rename the cheat files.
