### ISSUE TITLE
change.wav volume increases

### ISSUE THREAD

**Issue by TooGeekCreations** [OnionUI/Onion#1046]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

V4.2.0-RC-Snapshot-BS4BA37D

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

Miyoo Mini Plus
change.wav works fine on the main menu, if I go to the Applications menu iside Tweaks the volume for charge.wav increases maybe doubles. In any submenus in Tweaks no matter where you are the volume is still louder than normal. If you quit Tweaks menu the change.wav volume goes back to normal.

### Steps to Reproduce

See above

### Provide any additional context or information that may help us investigate your issue

Menu sound set to 10 from 20 for me in settings.

**Comment by XK9274** [comment]
Have you tried updating to the newest release? I'm on `v4.2.0-RC-snapshot-a5064207` and can't reproduce - if possible can you update and share a video if the issue still exists? Cheers

**Comment by Aemiii91** [comment]
I am able to hear a difference (when bgm vol in settings is set to 10)

**Comment by Aemiii91** [comment]
(In Tweaks, and all our other apps, we are not using the same volume formula as MainUI)

**Comment by TooGeekCreations** [comment]
> (In Tweaks, and all our other apps, we are not using the same volume formula as MainUI)

Oh, interesting...



> Have you tried updating to the newest release? I'm on `v4.2.0-RC-snapshot-a5064207` and can't reproduce - if possible can you update and share a video if the issue still exists? Cheers

I did update just now, oh boy now the applications are in different order what was before. (looks like random to me instead of alpabetic order) But the volume "problem" did not changed. Try it out to set the menu volume 02 and go in to the tweaks menu... the change.wav volume still louder there.
