### ISSUE TITLE
Battery status percentage obscured by wifi icon

### ISSUE THREAD

**Issue by pdzanek** [OnionUI/Onion#1051]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion-v4.2.0-RC-snapshot-4d182631

### Miyoo Firmware Version

202305052130

### Provide a clear and concise description of the issue

![battery](https://github.com/OnionUI/Onion/assets/34207245/0c77d656-0acc-493b-8c10-31442775a027)
The battery status is obscured by wifi icon as shown in the image. 

### Steps to Reproduce

System language: Polish
Device: Miyoo mini plus
I don't know if this is language-dependent or device-dependent. So it is possible that it occurs for other languages or for the miyoo mini.

### Provide any additional context or information that may help us investigate your issue

System language: Polish
Device: Miyoo mini plus

**Comment by XK9274** [comment]
Closing due to being a tracked issue with closed source frontend provided by Miyoo.  https://github.com/OnionUI/MainUI-issues/issues/6
