### ISSUE TITLE
Auto-resume last game broken

### ISSUE THREAD

**Issue by ffuuuuu** [OnionUI/Onion#1065]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion OS Beta 4.2.0-RC 244f4f8

### Miyoo Firmware Version

202305052130

### Provide a clear and concise description of the issue

When shutting down the device while in game, the game saves but when turning on it won't go back into the game as it did on earlier versions even though "Auto-resume last game" is turned on within Tweaks > System > Startup.

### Steps to Reproduce

Long press the power button or have "Power single press" set to "Shutdown" as I have. Turn it back on after it has successfully shut down. 

### Provide any additional context or information that may help us investigate your issue

It worked in earlier versions, went straight from the Beta to the latest RC on my MM+.

**Comment by Aemiii91** [comment]
Fixed in 9cff6bc
