### ISSUE TITLE
Bengali and Arabic language is unreadable in both miyoo mini and plus

### ISSUE THREAD

**Issue by abirvab** [OnionUI/Onion#1068]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

c4.2.0-RC-snapshot-d39af18f

### Miyoo Firmware Version

202302022130

### Provide a clear and concise description of the issue

@Aemiii91 @prokash-sarkar 
![20230726_120640](https://github.com/OnionUI/Onion/assets/5378948/235d4a26-7eb6-4fa9-8c4f-d03d1d819448)

I tried the Bengali language option in both Miyoo Mini and Plus. The text is displayed as boxes.
Please add support for the Bengali font or remove Bengali from the language option
The same happens for Arabic

Thanks

### Steps to Reproduce

Open the language menu from settings

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Aemiii91** [comment]
As far as I know, a font that contains absolutely all symbols in existence - doesn't exist!

At the moment, you have to modify the font manually.

- Download a multilingual font, [*Noto*](https://fonts.google.com/noto/fonts) for example.
- Copy the font to `SD:/miyoo/app`.
- Edit the theme's config.json and set the list font:

`SD:/Themes/Silky by DiMo/config.json`
```json
"list": {
    "font": "/mnt/SDCARD/miyoo/app/NotoNaskhArabic-VariableFont_wght.ttf",
    "size": 25,
    "color": "#FFFFFF"
}
```
