### ISSUE TITLE
Sort Apps list in MainUI

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#108]
it's sorted by how it's been added to the filesystem (creation date probably)
I have tested the `touch` command without success but `mv` seems enough to change the creation date. 

We could make a little script to order it but an entry in Tweaks -> Tools would be better 🤔

[Discord conversation about it](https://discord.com/channels/529983248114122762/1007796369785897090/1024775482836779050)

Finally the creation date of folders are all the same when we work on FAT32 with the Miyoo Mini.... So no solution for now.

**Comment by Aemiii91** [comment]
Added in https://github.com/OnionUI/Onion/pull/1300
