### ISSUE TITLE
Menu falsely shows duplicate ROMs

### ISSUE THREAD

**Issue by dothackjhe** [OnionUI/Onion#1123]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0-RC

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

Navigating the list of ROMs on Retroarch shows multiple copies (usually just two, but sometimes more) of the same ROM. But checking the ROMs directly on the micro-SD Card shows no duplicates at all. 

Consequently, this ties in with the previous bug report I made regarding the system not doing anything when trying a delete a ROM: https://github.com/OnionUI/MainUI-issues/issues/15

I might be attempting to delete a "phantom ROM," hence why the functionality does not seem to work. 

### Steps to Reproduce

Simply navigate the list of available ROMs, regardless of the system. But in my experience, it's with GBA and SNES.

### Provide any additional context or information that may help us investigate your issue

Already stated.

**Comment by Aemiii91** [comment]
You need to refresh roms after deleting files. If you're seeing 'phantom' files, your card must be corrupted.
