### ISSUE TITLE
CPU frequency scaling cpu underclock

### ISSUE THREAD

**Issue by SlowPixel** [OnionUI/Onion#1126]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion V4.2.0-RC

### Miyoo Firmware Version

Last

### Provide a clear and concise description of the issue

Will it be possible to lower and increase the frequency of the processor?
I use Koriki and there is this feature, it saves battery very well when I play NES or watch movies. I would like to see it in future versions.

### Steps to Reproduce

Please) 

### Provide any additional context or information that may help us investigate your issue

Please)

**Comment by Aemiii91** [comment]
Not a bug. Already in RC.
