### ISSUE TITLE
Region variables not correct in scrap_screenscraper.sh

### ISSUE THREAD

**Issue by kylepaulsen** [OnionUI/Onion#1141]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion V4.2.0-RC

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

I was playing around with the new screenscraper script file ( [scrap_screenscraper.sh](https://github.com/OnionUI/Onion/blob/860fb397bf2b99b3e33bbc59880eb812df107eb8/static/build/.tmp_update/script/scraper/scrap_screenscraper.sh) ) that was recently merged because I was noticing I was getting incorrect box art files. 

Then I noticed there was a capitalization typo in the script. All the region variables seem to be wrong:
https://github.com/OnionUI/Onion/blob/860fb397bf2b99b3e33bbc59880eb812df107eb8/static/build/.tmp_update/script/scraper/scrap_screenscraper.sh#L479

### Steps to Reproduce

Look at the code I guess. I'm pretty sure it's a typo.

### Provide any additional context or information that may help us investigate your issue

No other info really, but it would be pretty cool if the scraper script could also be run from the favorites menu. Also would be awesome if you could manually search and select a url to download if the auto search failed.

**Comment by schmurtzm** [comment]
Thank you very much, [fixed](https://github.com/OnionUI/Onion/commit/60559919de90644350d7205cf8e118f0524f0e67#diff-328a2747701aed9046c5eb3e008b3e2f7ce2808adf57ab18c5b058ca9f45e349) in Onion 4.2.3.
