### ISSUE TITLE
GBA Netplay multiplayer not working 

### ISSUE THREAD

**Issue by Amendoleaa** [OnionUI/Onion#1148]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2

### Miyoo Firmware Version

20230326339

### Provide a clear and concise description of the issue

Communication between two devices doesn't work with Netplay playing GBA roms as Pokèmon Ruby/Sapphire or Fire Red/Leaf Green (Battle or Trade)

### Steps to Reproduce

Wifi On ; Right IP address ; Right communication in other Roms (GB/GBC)

### Provide any additional context or information that may help us investigate your issue

_

**Comment by XK9274** [comment]
We don't have any netplay capable GBA cores at the minute. The cable link (pokemon trading etc) only works for GB/GBC games currently through TGB Dual.

https://docs.google.com/spreadsheets/d/1y1esG3HcNagPG8cy-ulZK_mhhUb93pqG5_XEtRRgKQ4/edit#gid=0

The list may be filtered when you arrive on it

![image](https://github.com/OnionUI/Onion/assets/47260768/28bc0192-2e6c-48ac-b09c-1ebba51e1a9a)
