### ISSUE TITLE
Update Retroarch to 1.18

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#1214]
- RA 1.17 will fix many Netplay bugs/freezes/black screens (Thanks David for that !)
- The gpSP core will be updated with multiplayer support
- Network commands will be enabled to allow easy arcade exit with menu button (https://github.com/OnionUI/Onion/issues/1162)
- Sound for retroachivements could be enabled if there are no side effect (https://github.com/OnionUI/Onion/issues/770)

**Comment by AceFlo777** [comment]
Will this allow for wireless trade between GBA Pokemon games? Maybe via gpSP core?

**Comment by shays7** [comment]
Can you then trade Pokemons on the GBA, like on the GBC and GB??? It would be absolutely awesome.

**Comment by joshkim-wustl** [comment]
> Can you then trade Pokemons on the GBA and NDS, like on the GBC and GB??? It would be absolutely awesome.

Apparently yes, according to this video https://www.youtube.com/watch?v=ih0cbeg4mfY
