### ISSUE TITLE
Canceling search - Program exited unexpectedly

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [OnionUI/Onion#1261]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.3

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

Exiting the search form results in a unexpected error

### Steps to Reproduce

Press X (top button) to search and when the search term input comes up just press B (bottom button) to cancel and you will be seeing the screen “The program exited unexpectedly. (Error code: 139)”

### Provide any additional context or information that may help us investigate your issue

I update using OTA updater to 4.2.3

**Comment by sanderDijkxhoorn** [comment]
![F37B343C-8DB1-492D-BF28-C2452C549465](https://github.com/OnionUI/Onion/assets/15117158/4d170333-d3a7-42bf-8e4e-66d0ae8f6fd1)

**Comment by sanderDijkxhoorn** [comment]
There is also a kind of similar issue reported on the MiyooMini Reddit: [Reddit post](https://www.reddit.com/r/MiyooMini/s/EjR7Pvlxl3)

**Comment by sanderDijkxhoorn** [comment]
I switched my theme from this Cyber one back to the onion default and then again back to cyber one and it works fine again.

**Comment by Aemiii91** [comment]
So weird.. glad it's working now though
