### ISSUE TITLE
Missing Favourites sorting

### ISSUE THREAD

**Issue by Goodingn** [OnionUI/Onion#1296]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.3

### Miyoo Firmware Version

X

### Provide a clear and concise description of the issue

In v4.1.x there used to be a tweak to sort favourites, this is missing in v4.2.x

### Steps to Reproduce

Missing

### Provide any additional context or information that may help us investigate your issue

Missing

**Comment by Aemiii91** [comment]
It's not missing. It has moved to GLO.

**Comment by Goodingn** [comment]
What is GLO?

**Comment by Goodingn** [comment]
Thanks. Maybe 'Y Options' needs to be on the screen next to 'A select B back'?

**Comment by Aemiii91** [comment]
Not possible, frontend is closed source.

**Comment by szechp** [comment]
In the latest beta 4.4 this sort option on the glo launches the game. No sorting is done

**Comment by fengfrw** [comment]
> In the latest beta 4.4 this sort option on the glo launches the game. No sorting is done

In the new version of GLO, some options will automatically run the game after execution. If you need not execute the game, you can add the following code to the relevant script:
sysdir=/mnt/SDCARD/.tmp_update
rm -f $sysdir/cmd_to_run.sh 2> /dev/null
exit 0

**Comment by szechp** [comment]
Alright fair, but it doesn't sort favorites for me anyway :/

**Comment by fengfrw** [comment]
I have tested it, and it works normally according to the system default or sorted by A-Z.

**Comment by szechp** [comment]
are you on Onion V4.4.0-beta-20260120?
