### ISSUE TITLE
Game List Alphabetical Sorting Bug

### ISSUE THREAD

**Issue by HapHzrd** [OnionUI/Onion#13]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.2

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

It seems that the alphabetical sorting for the games lists are case sensitive.
For example, it will sort "seaQuest DSV" to the end of the list after "Zoop" instead of sorting it with the capital "S" games.

### Steps to Reproduce

Look at any game / game list that have games that begin with a lowercase letter.  Examples:
- _Gameboy_ has "**seaQuest DSV**" you can test with.
- _Gameboy Advance_ has "**bit Generations**" to test with.
- _Gameboy Advance_ has "**xXx**" to test with.

### Provide any additional context or information that may help us investigate your issue

Apologies if this is not the correct way to report this bug.  You devs have done a great job with this software.

**Comment by Olywa** [comment]
Hi there, no need to apologise, you logged the issue correctly :)

This is a (known) bug but unfortunately not one that Onion introduces (it's the same in Miyoo Stock OS). It has to do with the fact Linux is case sensitive and treats the files this way. It has been previously reported to Miyoo in the hope they fix it in a future firmware release but it would be a lot of work to correct it in Onion so it's not on the roadmap for now.

There are some workarounds, you have two options.
- You can rename your files to be capitalised (see below)
- You can use the [miyoogamelist.xml feature](https://github.com/OnionUI/Onion/wiki/3.-FAQ-(Frequently-asked-questions)#how-to-rename-your-roms-using-a-gamelistxml-and-convert-it-to-a-miyoogamelistxml-which-onion-can-use) to build a game list for the console(s) that uses correct, capitalised names. 

The first is the quickest approach and can be easily done with third party 'bulk rename' utilities but I've created a quick batch script for you which you can use on Windows. Just extract the .bat file to the same folder as your Roms and double click it to run. It will rename every file to have a capital first letter. You should probably run it inside the Imgs folder too for any systems you apply it on (so the rom filenames will still match exactly any artwork). 

It is not recommended to rename arcade based roms (Mame, Final Burn, NeoGeo or CPS1/2/3) as renaming will break those. The best way for Arcade based systems is to use the [miyoogamelist feature](https://github.com/OnionUI/Onion/wiki/3.-FAQ-(Frequently-asked-questions)#how-to-rename-your-roms-using-a-gamelistxml-and-convert-it-to-a-miyoogamelistxml-which-onion-can-use). 
 
[Capitalize-Files-Script.zip](https://github.com/OnionUI/Onion/files/9115546/Capitalize-Files-Script.zip)

I hope this helps.
