### ISSUE TITLE
Build branch 'main'

### ISSUE THREAD

**Issue by belmix** [OnionUI/Onion#1319]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.3

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

Build branch 'main'
tweaks - utilities (error)

### Steps to Reproduce

Apps - tweaks - utilities (error)

### Provide any additional context or information that may help us investigate your issue

![Tweaks_001](https://github.com/OnionUI/Onion/assets/4902701/5982565f-97ba-4398-be44-af2b97d7dd45)

**Comment by XK9274** [comment]
Hey,

We're aware of it - there's still some outstanding PR's to be merged that will fix it. cheers

**Comment by XK9274** [comment]
Resolved when NUM_TOOLS was updated.
