### ISSUE TITLE
save thumbnail not work on gpsp

### ISSUE THREAD

**Issue by Luvmaya** [OnionUI/Onion#134]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.0

### Miyoo Firmware Version

20220419

### Provide a clear and concise description of the issue

when I save in state with gpsp, thumbnail screenshot created in states folder, but not shown in retroarch.

### Steps to Reproduce

save in gpsp and check state thumbnail

### Provide any additional context or information that may help us investigate your issue

none

**Comment by Aemiii91** [comment]
Not anything we can fix. You can press Y to view the thumbnail in fullscreen.
