### ISSUE TITLE
GameSwitcher crashes when showing games which overwrite MENU button for their own ingame menu 

### ISSUE THREAD

**Issue by Hanfos** [OnionUI/Onion#1350]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0-beta2

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

- GameSwitcher instantly crashes when u open it and the last game u played was a game which overwrites the MENU button to make it open its own ingame menu <sub>(where u can also leave the game)</sub>

- When a normal game is the last played game GameSwitcher crashes when it has to show up a 2nd MENU button overwriting game 

### Steps to Reproduce

> **MBG** = MENU button overwriting game
> **NG** = normal game which doesnt overwrite MENU button
> **→** = right arrow button to show the next last played saved game
> **GS** = opening GameSwitcher from onion 

Now how I reproduced after going in the GS from onion home by pressing MENU button:

<sup>1st game is MBG: </sup>
CRASH

<sup>1st game is NG, 2nd MBG, 3rd NG, 4th MBG :</sup>
→→→ CRASH

### Provide any additional context or information that may help us investigate your issue

The 2 MBG games I tested are:
Done Set -> PORTS -> FPS - Duke Collection (eduke32) -> **Duke nukem 3D** & **Duke Nuclear Winter**

**Comment by tGecko** [comment]
Can you still reproduce on 4.3.0 stable?
Seems to work just fine here. 

https://github.com/OnionUI/Onion/assets/6023076/16f067e9-4c87-401e-a0f0-aca8e1defe1d
