### ISSUE TITLE
Gallery App not finding any screenshots after Tweaks/Advanced/Reset Everything

### ISSUE THREAD

**Issue by bteamfox** [OnionUI/Onion#1386]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0 Beta 8ae761fc

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

After running reset everything Gallery app will not find any screenshots.

### Steps to Reproduce

I stupidly created a New Configuration File in retro arch.
Then starting C64 games there was no sound. Game showed yellow notification on startup, (sorry didn't take note of message).
I did not know how to fix it.
I went to Tweak/Advanced/Reset Everything.
Then Gallery would not find any screenshots.
I uninstalled and reinstalled Gallery via Package manager
Now it shows two images Corrupted (1/257), (2/257) then when you tap right a third time it displays "No screenshots found"

### Provide any additional context or information that may help us investigate your issue

I have tried uninstalling and reinstall Gallery and rebooting in between a few time but this has not helped.
I noticed the two images that are displayed as corrupted are the first two screenshots. I tried deleting the first two images but that did not help. It just shows the new first two images as corrupt.
I have attached three images of the UI so you can see what is happening.
I have also attached my full screenshot folder. I don't think there is any corruption.

Using File Explorer app screenshots appear correct as they do on my windows PC.

So it appears running Reset Everything has done something? I know Onion OS version 4.2.3 it was working. But had not tried it in Beta 4.3.0 until I ran reset everything.

[Main UI Screenshots.zip](https://github.com/OnionUI/Onion/files/13998598/Main.UI.Screenshots.zip)
[Screenshots Folder.zip](https://github.com/OnionUI/Onion/files/13998599/Screenshots.Folder.zip)

**Comment by XK9274** [comment]
Adding more info for when there's time for one of us to check:

Reproduced after resetting everything, but only with using your screenshot folder you attached and only when it tries to load an odd sized image (not 640x480). - worked fine with my screenshots dir after resetting (all 640x480)

![image](https://github.com/OnionUI/Onion/assets/47260768/bfe5965b-8532-436f-80c9-f32c5bcc65bd)

Seg faults:
![image](https://github.com/OnionUI/Onion/assets/47260768/77fa4529-0877-4f14-8896-9074f525043b)

Then loads the infoPanel here: 
https://github.com/OnionUI/Onion/blob/52d56cc7498e7aa58627f9bdbb0c0d92d4d8f301/static/packages/App/Gallery%20(Screenshot%20viewer)/App/Screenshots_Viewer/launch.sh#L12
![Screenshots_Viewer_000](https://github.com/OnionUI/Onion/assets/47260768/5df13ef0-33c1-44a2-ad84-90c1c837c931)


All Assembloids load fine, Battlezone 2000 does not.
|  |  |
|---|---|
| ![Image 1](https://github.com/OnionUI/Onion/assets/47260768/3ca3e435-f25d-4c46-8685-2f30479f0b5d) | ![Image 2](https://github.com/OnionUI/Onion/assets/47260768/7ee4eaae-40cc-4f17-a95e-f9c08d394918) |
