### ISSUE TITLE
Unable to download OTA through 4.3.0...e33 to 4.3.0...326

### ISSUE THREAD

**Issue by Amiga500** [OnionUI/Onion#1390]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0-RC-6e310e33

### Miyoo Firmware Version

202105052130

### Provide a clear and concise description of the issue

Trying to update via OTA from 4.3.0-RC-6e310e33 to latest one (75c2b326) is not possible to download latest version. Pressing A t the screen come back to App list page
![36c2983635300868f58c3599047b5c75bc1df93eef850982670cfb4773d60a65](https://github.com/OnionUI/Onion/assets/16525337/65e5bda8-4225-4ece-96a1-934aece57cda)

### Steps to Reproduce

Please provide detailed steps that will help us replicate and investigate your issue

### Provide any additional context or information that may help us investigate your issue

no

**Comment by Aemiii91** [comment]
I'm very sorry, but a bug slipped through to the OTA update script. If you updated to `6e310e33`, you'll either need to install Onion manually (via file transfer), or replace `.tmp_update/script/ota_update.sh` with the [latest one](https://github.com/OnionUI/Onion/blob/main/static/build/.tmp_update/script/ota_update.sh)

**Comment by Aemiii91** [comment]
If you're completely out of luck and can't use manual file transfer, then a workaround could be to fix the `ota_update.sh` script in the on-device File Explorer.

Simply replace `Release_size_bytes` with `Release_size` (case-sensitive) as seen on line 132 and 133 below:

![image](https://github.com/OnionUI/Onion/assets/44569252/9967bdfd-48c1-4db5-b9c3-9bfb3e6be2e7)

In File Explorer (`.tmp_update/script/ota_update.sh`):

![Commander_Italic_000](https://github.com/OnionUI/Onion/assets/44569252/3e0e1cc4-460b-4619-91f5-da09c437649b)

**Comment by Amiga500** [comment]
Thanks for the explanation Aemiii91, i had resolved with two manual updates. 
Keep up with this fantastic work on Onion!
