### ISSUE TITLE
Video Player 16:9 default instructions don't match current Onion OS file structure

### ISSUE THREAD

**Issue by jwithington** [OnionUI/Onion#1396]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://onionui.github.io/docs/apps/video-player#advanced

### Description

The *Advanced* section includes instructions for forcing 16:9 to be the default.

It points to the folder `Emu/ffplay/bin`, but this folder doesn't exist. See screenshot; it looks like the main FFplay folder is in App now. In addition, I don't see any `bin`. 

![image](https://github.com/OnionUI/Onion/assets/4213550/42778e40-d619-486e-b64f-35b187496644)

### Correction

Should update with how to do this in the newer version of Onion. 

### Provide any additional context or information that may help us with this update

I'm doing this on a Mac, v4.2.3.

**Comment by XK9274** [comment]
Thanks for submitting! added to another docs branch to merge for 4.3 - As a side note we should have an easier way to toggle this i think. 

https://github.com/OnionUI/Onion/commit/138afd8cede1f3d692c4533bd0df340f20b27ce8
