### ISSUE TITLE
PICO-8 Fails to launch

### ISSUE THREAD

**Issue by FDrebin** [OnionUI/Onion#1397]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0-RC-b66469de (current beta)

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

PICO-8 fails to launch , see anttached image.
Previously worked on first version with PICO-8 wrapper.

### Steps to Reproduce

install PICO-8 with native files and wrapper. 

### Provide any additional context or information that may help us investigate your issue

Photo

![IMG_5500](https://github.com/OnionUI/Onion/assets/13129353/cee0f1eb-8f26-4985-b756-3b5099fc34b9)

**Comment by XK9274** [comment]
If you're on Onion 4.3 RC you shouldn't need to re-add the wrapper to the Apps dir as it's built in to Expert. (apart from the binaries..)

# PICO-8

## PICO-8 standalone can now be installed from the Expert section in Package Manager. Remember to move your binary files into the new dirs:

- These binaries will need to be added to: /mnt/SDCARD/RApp/PICO-8/bin

- Any saves and config will go to: /mnt/SDCARD/Saves/CurrentProfile/saves/PICO-8

- Carts will follow the default Onion path: /mnt/SDCARD/Roms/PICO

- Splore carts will be stored in: /mnt/SDCARD/Roms/PICO/splore

- Favourites.txt (if you want to move it) should go in: /mnt/SDCARD/Saves/CurrentProfile/saves/PICO-8/.lexaloffle/pico-8/

**Comment by TheodorDzhoglev** [comment]
I am experiencing the same issue as well. I am to the latest Onion and I have added my binaries, but still have the same message as FDrebin. I will try manually to fixed it as he explained. I had the wrapper working fine before the new Onion update.
