### ISSUE TITLE
Low volume headphones

### ISSUE THREAD

**Issue by mcfly90** [OnionUI/Onion#141]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

April 2022

### Provide a clear and concise description of the issue

I plug diferent brands of headphones and the volume is low on games, very low

### Steps to Reproduce

plug any headphones on miyoo mini v2

### Provide any additional context or information that may help us investigate your issue

Fix the low volume on Miyoo mini v2 Onion Os 4.0.3

**Comment by Aemiii91** [comment]
Not possible to fix. Best we can do is the volume boost: https://github.com/OnionUI/Onion/wiki/Global-Shortcuts
