### ISSUE TITLE
Please made version of Onion Os with shaders active and other without option

### ISSUE THREAD

**Issue by mcfly90** [OnionUI/Onion#142]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

April 2022

### Provide a clear and concise description of the issue

I want to put shaders on gameboy, gba, game gear games, etc, but the option don't work, please active this option

### Steps to Reproduce

Shaders on gameboy games

### Provide any additional context or information that may help us investigate your issue

With 2 option of Onion Os, one with the option on and other off, make happy to many, please

**Comment by Aemiii91** [comment]
Not possible on miyoo mini, shaders require GPU.
