### ISSUE TITLE
Generating short name roms list leaves quote marks at end of names

### ISSUE THREAD

**Issue by ourigen** [OnionUI/Onion#1426]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

v4.3-RC-b66469de

### Miyoo Firmware Version

202306092122

### Provide a clear and concise description of the issue

Generating game list for short name roms leaves an extra quotation mark at the end of names. From my testing, this happens with Neo Geo and Arcade roms.

### Steps to Reproduce

Apps > Tweaks > Tools > Generate game list for short name roms. Then check the rom list for either Arcade or Neo Geo

### Provide any additional context or information that may help us investigate your issue

![304597569-2c16f54c-558c-4c94-a90a-182c276fd05f](https://github.com/OnionUI/Onion/assets/79729735/8e791520-9f13-4557-b8b1-ae165a20548a)

**Comment by Aemiii91** [comment]
![MainUI_016](https://github.com/OnionUI/Onion/assets/44569252/79f5fcaf-5046-47f5-9e7a-adf97ff3a06a)

Works fine for me. Maybe you edited the arcade names file and have the wrong line endings (CRLF instead of LF).
