### ISSUE TITLE
Quick menu background are black after using the Theme app to switch themes

### ISSUE THREAD

**Issue by hungtcs** [OnionUI/Onion#143]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

Black background when open quick menu (default is translucent).

### Steps to Reproduce

1. Switch theme use the "Theme" app
2. Press select button in main ui or list ui.

### Provide any additional context or information that may help us investigate your issue

![MainUI_000](https://user-images.githubusercontent.com/11692935/192321664-a181c8fd-a4bf-4471-9e39-7d4184db0951.png)
![MainUI_001](https://user-images.githubusercontent.com/11692935/192321669-37275b8d-f5dd-4280-ba92-24665c2d931f.png)

**Comment by hungtcs** [comment]
More Step：
1. Turn off and eject memory card
2. Turn on and `Settings -> Factory Reset`
3. Turn off and insert memory card 
4. Turn on and press `Select` button to open quick menu (now the quick menu background is translucent)
5. Switch theme use `Themes` app. (now the quick menu background is black)

----



![MainUI_002](https://user-images.githubusercontent.com/11692935/192326342-641c0b95-fb5a-4e3f-bef5-705bd9284fae.png)
![MainUI_003](https://user-images.githubusercontent.com/11692935/192326346-84195c3e-9359-449f-ac0c-c024d8bfdb4d.png)

**Comment by Aemiii91** [comment]
This issue is apparently theme specific. Since themes are user-generated content, it's not an issue we can address at this moment.
