### ISSUE TITLE
Changed app icon will be reverted after using guest mode

### ISSUE THREAD

**Issue by murmelbahn** [OnionUI/Onion#1438]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0 

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

Hi,
I'm using icons for some of my apps which are not part of the main theme.
After using the guest mode the app icons are reverted to the default app icons.

### Steps to Reproduce

Go to Tweaks -> Apperance -> Icon packs -> Edit app icon 
Set an alternativ icon for Onion OTA update
Activate guest mode
Deactive guest mode
Check the icon in the App menu.

### Provide any additional context or information that may help us investigate your issue

-

**Comment by Aemiii91** [comment]
This is just a limitation, not a bug.
