### ISSUE TITLE
PSX screen contracted

### ISSUE THREAD

**Issue by Vclaiton** [OnionUI/Onion#1440]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0

### Miyoo Firmware Version

202305052130

### Provide a clear and concise description of the issue

After updating to 4.3.0 in some PSX games The screen show a contracted image.

### Steps to Reproduce

Please provide detailed steps that will help us replicate and investigate your issue

### Provide any additional context or information that may help us investigate your issue

X2 game for example.

**Comment by Aemiii91** [comment]
What do you mean contracted? Shrinked? Can you attach some screenshots?

**Comment by Vclaiton** [comment]
> What do you mean contracted? Shrinked? Can you attach some screenshots?

Yes, shrinked. English is not my language. In some parts of the game the image is ok, in others are shrinked. I will put the images.![IMG_20240225_125747.jpg](https://github.com/OnionUI/Onion/assets/81134162/3421adb9-0181-479c-a171-83b7568fd1c5)

![IMG_20240225_125724.jpg](https://github.com/OnionUI/Onion/assets/81134162/e10df09e-2648-4c8a-8a22-42d589019aa7)

![IMG_20240225_125729.jpg](https://github.com/OnionUI/Onion/assets/81134162/4fb87dfc-8473-4970-986d-844d89775825)

![IMG_20240225_125710.jpg](https://github.com/OnionUI/Onion/assets/81134162/f1956c45-3302-4d4c-8777-6b8f9df7d7a6)

**Comment by Aemiii91** [comment]
And you're absolutely sure that these games didn't render this way before you updated?

**Comment by Vclaiton** [comment]
> And you're absolutely sure that these games didn't render this way before you updated?

Yes, absolutely. I have played they yesterday. Same ROMs, I didn't nothing after playng, and after I updated.

**Comment by tGecko** [comment]
Which Formula 1 game is this?

**Comment by Vclaiton** [comment]
> Which Formula 1 game is this?

The first one of the Psygnosis for the PSX. 1995 season.

**Comment by tGecko** [comment]
After testing I can reproduce this, but I can also reproduce it with Onion 4.2.3. This is an inherent issue with PCX-ReARMed and Playstation games sometimes running in half or full height. 

To fix this, please press Menu + Start to cycle through the display modes, and select "Integer scaling: On (4:3)"
