### ISSUE TITLE
Expert tab breaks retrorama theme

### ISSUE THREAD

**Issue by billm555** [OnionUI/Onion#1450]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0 stable 

### Miyoo Firmware Version

202305052130

### Provide a clear and concise description of the issue

With the expert tab enabled and the retrorama theme active, scrolling left or rights breaks categories (get half an image) continued scrolling  sometimes fixes them breaks again

### Steps to Reproduce

See above

### Provide any additional context or information that may help us investigate your issue

See above

**Comment by Aemiii91** [comment]
Not a bug. It's a known limitation. Also, you just ignored the checklist above, huh?
> Any issues with the closed source frontend (MainUI),
