### ISSUE TITLE
GameSwitcher never displays FF8 PBP

### ISSUE THREAD

**Issue by dovahkiin** [OnionUI/Onion#1451]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0

### Miyoo Firmware Version

2022 04 19 0828

### Provide a clear and concise description of the issue

Final Fantasy VIII (USA) in PBP format runs perfectly, but it fails to show up in the Game Switcher.

The file is 2.05GB (2,212,443,740 bytes). It is the only ROM file I have which is over 2GB and seems to be the only one with this issue.

Clearing the recentlist.json file and other history JSON files has no effect. Logs (when enabled) also show no issue.

Renaming the ROM file, or changing a few bytes in it does not seem to help. I tried slicing the end off the file so it was just under 2GB and of course this fails to boot but it _does_ show up in the Game Switcher.

FF8 shows up OK in the JSON file, and it's screenshot is saved in romScreens, but it's entry doesn't show up and isn't selectable. Interestingly, the game after it in the JSON list displays FF8's screenshot.

Other people on reddit seem to have the same issue:
https://www.reddit.com/r/MiyooMini/comments/149wctj/question_about_psx_pbp_files/
https://www.reddit.com/r/MiyooMini/comments/zf1kcd/game_wont_appear_in_switcher/

From what I can see, signs point to it being related to the ROM file being over 2GB.

### Steps to Reproduce

1. Load up Final Fantasy VIII (USA).pbp
2. Open the Game Switcher
3. FF8's screenshot will appear over the next game in the list and FF8 itself isn't displayed

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by tGecko** [comment]
Thanks for the report - we think we have issued the root cause and will provide a fix in the next update.
