### ISSUE TITLE
NDS not listed in AdvanceMenu

### ISSUE THREAD

**Issue by WoxWik** [OnionUI/Onion#1453]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

Advancemenu does not list the NDS emu 

### Steps to Reproduce

Open advencemenu app, press start, look for nds

### Provide any additional context or information that may help us investigate your issue

N/a

**Comment by Aemiii91** [comment]
It's there for me.

![Screenshot_001](https://github.com/OnionUI/Onion/assets/44569252/3af8d056-bed2-4d22-8d79-97fff200798a)
