### ISSUE TITLE
Roms search itility does not add Bin images of PS1 games to game list.

### ISSUE THREAD

**Issue by kivarun** [OnionUI/Onion#146]
According this https://www.youtube.com/watch?v=QWSQrMeo7mU games in bin format are working well on the device. 
Please add .bin to the allowed img formats

**Comment by Olywa** [comment]
`.bin` files are currently supported in Onion v4 but this may change in the future. 

The Onion team strongly recommends having `.cue` files paired with each of your `.bin` files. This is the standard and the way in which these files are intended to be used. If you are missing .cue files, they can be [easily generated here](https://www.duckstation.org/cue-maker/).
