### ISSUE TITLE
Easy Netplay using GLO after a search doesn't launch

### ISSUE THREAD

**Issue by XDarkBringX** [OnionUI/Onion#1461]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

MM+ on 4.2.3 and 4.3

### Miyoo Firmware Version

202303292051

### Provide a clear and concise description of the issue

I used the search feature to look up a game and try to launch GLO easy netplay after selecting a game. When it says creating hotspot, right after it just says cleaning up and boots me back to game selection. I tried it with a few games (contra 3, Super Mario bro 3, Mortal Kombat 3) using the search and all fail, but when I manual go into SNES folder and scroll to those games and GLO easy netplay it works.

### Steps to Reproduce

Use search feature
select a netplay-able game
GLO easy netplay
it attempts to create hotspots but gets booted

### Provide any additional context or information that may help us investigate your issue

hosting a standard netplay through search feature works.

**Comment by XK9274** [comment]
This will be fixed when https://github.com/OnionUI/Onion/pull/1541 merges - thanks for letting us know
