### ISSUE TITLE
Option to hide recent or favorites tab

### ISSUE THREAD

**Issue by mrjoshw408** [OnionUI/Onion#150]
Feature request: Allow the ability to disable the recent or favorites tab from the main menu. This option can be in the settings menu.

**Comment by Olywa** [comment]
@Aemiii91 Recent of course can be hidden now (since v4) do we also want a toggle also to hide Favorites? 
Not sure if this could have an impact on Themes (if say Expert, Recent and Favorites were all hidden, leaving only three tabs)?

**Comment by Aemiii91** [comment]
That's not going to happen, then we have to juggle too many different MainUI binaries. It's not possible to toggle favorites the same way we did recents.
