### ISSUE TITLE
Update EasyRPG core extension support

### ISSUE THREAD

**Issue by bmn001** [OnionUI/Onion#1520]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://onionui.github.io/docs/emulators/easyrpg

### Description

Current article says only .easyrpg extensions are supported.

They are, but the [official docs](https://docs.libretro.com/library/easyrpg/) for this core say that it also supports .ldb and .zip.

I've confirmed .zip files do work, just as long as the `RPG_RT.ini` and `RPG_RT.ldb` are in the root folder of the archive.

### Correction

Extensions: `.zip`, `.ldb`, `.easyrpg`

**Comment by tGecko** [comment]
I think #1507 is what you're asking?

**Comment by bmn001** [comment]
Ah yep, looks like!  Thank you!

**Comment by Aemiii91** [comment]
Issue will be closed when PR is merged
