### ISSUE TITLE
Mouse doesn't go all the way left on Pico-8 Standalone

### ISSUE THREAD

**Issue by LuisGustavo78** [OnionUI/Onion#1526]
### Checklist

- [x] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

When trying to play a game that uses " Mouse Mode " on the Pico-8 standalone, by pressing L2, the mouse can move normally to the right, top, and bottom parts of the screen. But can't move to the left part of the screen.

### Steps to Reproduce
• Go to the expert menu
• Go to " Pico-8 Standone " 
• Start a game that supports mouse mode on the pico-8 Standone
• Press " L2 " and move the mouse to the left

### Provide any additional context or information that may help us investigate your issue

It is important to say that this bug did not exist in the separate github version: 
" https://github.com/XK9274/pico-8-wrapper-miyoo "
 looks like it happened after the changes of screen params in Onion OS 4.3

**Comment by XK9274** [comment]
https://github.com/OnionUI/Onion/pull/1535
