### ISSUE TITLE
ScummVM Land of Lore missing or corrupted KYRA.DAT file (Solution)

### ISSUE THREAD

**Issue by pommidorka** [OnionUI/Onion#155]
After I replaced the file from the memory card with [this one](https://github.com/scummvm/scummvm/blob/branch-2-6/dists/engine-data/kyra.dat), everything worked.

![image](https://user-images.githubusercontent.com/7317988/176440517-f0548a56-fe11-49e1-839f-9b00ac3f655b.png)

**Comment by Olywa** [comment]
@schmurtzm I think maybe you already solved this in your latest build (I vaguely recall something)?
