### ISSUE TITLE
Roms folders don't match Console names

### ISSUE THREAD

**Issue by zebramonkeylizard** [OnionUI/Onion#156]
Sega Genesis: Roms folder is MD
Nintendo: Roms folder is FC
Super Nintendo: SFC

There may be more, but I have these installed.

**Comment by casasfernando** [comment]
> > This is a missed opportunity to make the entire experience more intuitive and consistent. If the argument against updating it is that it's the Miyoo Mini default then why are there any differences between Onion OS and stock? Plus, there's the fact that EU MD games are PAL and US Genesis games are NTSC and run at different speeds and have different localisations so there's more to it than just the names.
> 
> And you can create different directories for all of them, by yourself It is not that hard…
> 
> i have split msx 1 and 2, gameboy and gameboy colour, wonderswan and wonderswan colour Really easy..

Sorry to resurrect this conversation but I was looking into how to do this myself for convenience and I have a couple of questions I hope someone can address:

1. Is there any guide or howto I can use as a reference on which files/scripts need to be modified to and how they need to be modified? I'm not very familiar with Onion OS specifics yet but I'm comfortable editing configuration files and scripts.
2. Will the changes survive an Onion OS update/upgrade or I would have to repeat the process every time after doing so?

Thanks
