### ISSUE TITLE
better GB GBC GBA Overlays

### ISSUE THREAD

**Issue by Benman2785** [OnionUI/Onion#1570]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

i modded GB GBC and GBA overlays so they look better and are pixel-accurate (actually the GBA overlay isnt - but its not possible otherwise)

### Steps to Reproduce

1. make backups of org *.png overlays
2. copy my overlays over
3. enjoy

### Provide any additional context or information that may help us investigate your issue

![GB](https://github.com/OnionUI/Onion/assets/21282980/14f8d1d2-d666-44a2-addb-001f48b74a20)
![GBA+3x+G1](https://github.com/OnionUI/Onion/assets/21282980/2ceb2fc9-b03e-4fd1-802a-a6cfc3124922)
![GBC-480P-final](https://github.com/OnionUI/Onion/assets/21282980/4c4e78ef-defe-4ff4-a977-66ab2bc9aa1b)

**Comment by XK9274** [comment]
Can you also PR this (In a separate PR to your german NDS lang)
