### ISSUE TITLE
FFplay Screen Tearing on Miyoo Mini Plus

### ISSUE THREAD

**Issue by kuzon3** [OnionUI/Onion#1600]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Current BETA

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

Screen tearing during video playback using ffplay. i'm assuming the issue has to do with vsync. enabling -framedrop in launch.sh helps a bit but screen tearing is still present.

### Steps to Reproduce

load a video hit play

### Provide any additional context or information that may help us investigate your issue

even tried changing the video fps to 60fps. even with that screen tearing was still present. i think i should say the original fps of the video is 23.976. even at that low of a fps screen tearing occurs

**Comment by Aemiii91** [comment]
We cannot fix this issue as we are not the developers or maintainers of the ffplay functionality.
