### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by Tenks86** [OnionUI/Onion#1668]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Probleme rom

### Miyoo Firmware Version

MY354

### Provide a clear and concise description of the issue

 Ma rom gba ne s'affiche pas dans la console gba mais elle s'affiche dans le menu advancemenu

### Steps to Reproduce

Please provide detailed steps that will help us replicate and investigate your issue

### Provide any additional context or information that may help us investigate your issue

 Ma rom gba ne s'affiche pas dans la console gba mais elle s'affiche dans le menu advancemenu

**Comment by Aemiii91** [comment]
Translated:

> My gba rom does not show up in the gba console but it shows up in the advancemenu

This is not the place to report this. Use Reddit or Discord.
