### ISSUE TITLE
Documentation has invalid firmware download link for MM+

### ISSUE THREAD

**Issue by dylanthall** [OnionUI/Onion#1671]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2

### Miyoo Firmware Version

N/A

### Provide a clear and concise description of the issue

Documentation on the "Install" panel has an invalid download link. 

https://github.com/OnionUI/Onion/blob/main/website/versioned_docs/version-4.2/02-installation/index.mdx

> 3. You need at least firmware version `20230505****`, if you have an older version please download the recommended firmware >linked below.
>
>   - `2023 02 18 1113` ⚠️
>   - `2023 03 02 1817` ⚠️
>   - `2023 03 12 1739` ⚠️
>   - `2023 03 26 2339` ⚠️
>   - `2023 03 29 2051` ⚠️
>   - `2023 05 05 2130` ✔️
>   - `2023 06 09 2122` ✔️
>   - `2023 06 28 2128` ✔️
>
>:::note Firmware downloads (MMP)
>
><IconLink href="https://app.sugarsync.com/iris/wf/D4978471_09235444_029620" icon="cloud_download">Firmware 20230609</IconLink>

### Steps to Reproduce

Go to the documentation, find MM+ firmware file, click to download, be engulfed in overwhelming sadness that it didnt work.

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by parataxia** [comment]
https://drive.google.com/file/d/1rA2-A0WdrP6za_xt_j-FOV1JZ5TPcxfj/view?usp=sharing

Here is a Google mirror for the FW file and simple instructions zipped within. Hope it works.
