### ISSUE TITLE
Easy Netplay not working 4.3.1-1

### ISSUE THREAD

**Issue by capsel22** [OnionUI/Onion#1688]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.1-1

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

I bought a second MM+ to play 2P games, however the Easy Netplay doesn't work. 
When second device uses the "Join a session", the device connects to the hotspot but fails on "Failed to download Rom file".

I have tried this on SNES and NEO GEO, on multiple games. I also tried different cores on SNES like the 2005_plus etc, however the easy netplay doesn't want to work.

However, the standard netplay works with no issues on all tested platforms and games.

Just to add, as a nuclear option. I have formatted both SD Cards, installed fresh OnionOS and copied exactly the same Roms to both SD cards. Those are identical.

I do apologise, I dont know how to find any debug logs, if someone would be so kind to let me know how to obtain them I will do my best to attach.

### Steps to Reproduce

First MM+
1. go to a game
2. press Y and go to Netplay -> Easy Netplay -> Host

Second MM+
1. go to a game
2. press Y and go to Netplay -> Easy Netplay -> Join
3. Device fails with "Failed to download Rom file." error

### Provide any additional context or information that may help us investigate your issue

![PXL_20241017_080410726](https://github.com/user-attachments/assets/1248474a-0abb-4b15-88cf-5ced572b8022)

**Comment by Aemiii91** [comment]
This should be fixed in the [latest](https://github.com/OnionUI/Onion/releases/tag/latest) pre-release
