### ISSUE TITLE
[Bug] NDS touch simulation goes on the wrong screen

### ISSUE THREAD

**Issue by light-and-ray** [OnionUI/Onion#1693]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.1-1

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

After switching between dual and single screen modes the touch simulation pointer appears on the wrong screen

### Steps to Reproduce

1. Open a game in dual screen mode. Touch works okay
![Screenshot_009](https://github.com/user-attachments/assets/d5bd5447-a8e0-45d2-aa90-029db417e113)
2. Switch to single screen (Menu+A for me, because I set dual screen in the settings as secondary mode)
![Screenshot_012](https://github.com/user-attachments/assets/a11974cb-ee26-4b0a-919c-94c87bcec5a2)
3. Right then press Menu+A again and go back to dual screen mode
4. Use touch simulation, and it's broken
![Screenshot_011](https://github.com/user-attachments/assets/3e0084ac-f393-4024-be8e-53a0b63f8e0b)

To fix it I need to close the game and open it again

### Provide any additional context or information that may help us investigate your issue

-

**Comment by Aemiii91** [comment]
The NDS emulator stems from this repository: https://github.com/steward-fu/nds - which in turn stems from DraStic. Please direct any issues to the appropriate owners.
