### ISSUE TITLE
Game Switcher Broken in v4.4.0

### ISSUE THREAD

**Issue by mrtekkid** [OnionUI/Onion#1724]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.4.0-8d8dc7ed

### Miyoo Firmware Version

202407211632

### Provide a clear and concise description of the issue

When playing a game (in my instance gameboy advance game) pressing the menu button to trigger game switcher does not work. Also power button is unresponsive.

### Steps to Reproduce

Please provide detailed steps that will help us replicate and investigate your issue

### Provide any additional context or information that may help us investigate your issue

When pressing the menu button Miyoo will buzz like it’s activating game switcher but does not display. Need to press select + menu to trigger retro arch menu and exit through there. Uncertain if saving in this state currently. Also the power button is non-functional until quit from the retroarch menu.

**Comment by tGecko** [comment]
Please do the following:

-  enable logging in Apps > Tweaks > Advanced > Diagnostics
- replicate the issues you have
- create a log snapshot from Apps > Tweaks > Advanced > Diagnostics
- upload the log_export.7z from the root of your SD card here

**Comment by jlnr** [comment]
I've had the switcher button break in 4.3.1 too, but could never figure out how to reliably reproduce it.

**Comment by tomahawk-k** [comment]
I have the same issue. Can only exit games by opening the retroarch menu
[log_export.zip](https://github.com/user-attachments/files/18227463/log_export.zip)

**Comment by Aemiii91** [comment]
@tomahawk-k thanks! Can you try resetting RA setting via **Apps -> Tweaks -> Advanced -> Reset settings** ?

**Comment by tomahawk-k** [comment]
@Aemiii91 Thank you! Resetting the main configuration worked and the game switcher is now working

**Comment by Aemiii91** [comment]
Alright, workaround confirmed. We're working on a permanent fix ✅

**Comment by devcodable** [comment]
Hello, reporting back from reddit with the logs. Additional info that may be interesting:

- When in game if I do an action involving power/menu buttons it only takes place once I quit retroarch (like power off or change game with double press)
- This is reproducible both in MM+ and MMv4, both in the latest firmwares for each one.
- Tried gba, gbc and arcade, it's reproducible in all of them

Thank you for the amazing work, if you need more debugging on my side please let me know.

[log_export.zip](https://github.com/user-attachments/files/18228271/log_export.zip)

**Comment by tGecko** [comment]
> ###
> **[devcodable](/devcodable) ** commented [Dec 23, 2024](#issuecomment-2559387689) •

Hey, thanks for your logs, please on your device in RetroArch/.retroarch/retroarch.cfg edit `network_cmd_enable = "false"` to `network_cmd_enable = "true"` then try again

**Comment by Aemiii91** [comment]
Fixed in 51bde3716341c07768e96a00686aaa129ba97b57
