### ISSUE TITLE
CPU frequency in About Device shown incorrectly

### ISSUE THREAD

**Issue by JordonVW** [OnionUI/Onion#1731]
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

V4.4.0-F384F5E7

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

I have applied an overclock by putting a cpuclock.txt file in the Retroarch folder for 1700MHz but the About Device section still shows 1200MHz which is misleading. The overclock works because the performance in game is improved. I understand some cores have individual clock speeds set but appears general overclock like mine could still be shown in the About Device section.

### Steps to Reproduce

Go to About Device section after applying a general overclock for Retroarch and it won't have changed. 

### Provide any additional context or information that may help us investigate your issue

An overclock toggle option similar to the LCD undervolt/overvolt would be a nice feature in the future too.

**Comment by tGecko** [comment]
This isn't an issue because the cpuclock.txt clock is only applied when RetroArch is running, not when navigating MainUI.
