### ISSUE TITLE
Launcher interface cannot display Chinese characters of file names

### ISSUE THREAD

**Issue by snodr** [OnionUI/Onion#176]
Launcher interface cannot display Chinese characters of file names
![MainUI_001](https://user-images.githubusercontent.com/81018733/173450043-75f6511a-e282-4557-99b6-2f8a0b15616f.png)

**Comment by Olywa** [comment]
@Aemiii91 This still appears to be an issue but not sure if it is within our control, seems Sicroteph believed it was.

**Comment by Aemiii91** [comment]
GameSwitcher supports theming since V4.0, this should be fixable by changing the font.
