### ISSUE TITLE
Launcher not working (crash to main menu)

### ISSUE THREAD

**Issue by SirPrimalform** [OnionUI/Onion#177]
I've been having a somewhat unpredictable problem with the launcher where sometimes it will stop working. It will start the last game at boot, but when I press the hotkey to go to the launcher menu I instead end up on the main menu. Trying to start the launcher with the shortcut in the apps folder just results in a momentary black screen before being returned to the menu screen I was just on.

Previous times the problem persisted until I did a clean(-ish) reinstall when upgrading to a new version of Onion. Is there any way to find out what's crashing it?

**Comment by Olywa** [comment]
@Aemiii91 I believe this should be closed but it might worth just a quick skim through for familiarity in case we ever see it again.
