### ISSUE TITLE
Favorites - Not alphabetical

### ISSUE THREAD

**Issue by zebramonkeylizard** [OnionUI/Onion#183]
Favorites (haven't tested game list) are not alphabetical. If I have a large Favorites list and I have to hunt for the game that defeats the purpose of the list.

**Comment by andornaut** [comment]
> will probably be added in the next onion release.

@Sichroteph any chance of this being added to the next Onion release?

**Comment by Aemiii91** [comment]
@andornaut you can sort favorites by pressing Y when in the list.
