### ISSUE TITLE
[Bug] Can't load games with a dollar sign in the name

### ISSUE THREAD

**Issue by aaldrich29** [OnionUI/Onion#186]
"WarioWare, Inc. - Mega Micro Game$" for the GBA would not load until I removed the dollar sign from the filename. Using default emulators in OnionOS.

**Comment by Olywa** [comment]
Closing this as there has been no update/resolution from Miyoo (I'm not convinced there ever will be).
For now it is at least [documented in our wiki here](https://github.com/OnionUI/Onion/wiki/Emulators#rom-files).
