### ISSUE TITLE
Game switcher uses default "key map" with every restart

### ISSUE THREAD

**Issue by Tortugasss** [OnionUI/Onion#19]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [x] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

Swapped L/R with L2/R2 in "settings --> key map". Launching a game normally uses them. When launched from game switcher (after a restart and until the game is normally launched), they are swapped back to default, ignoring my key map settings. Haven't tried other buttons.

### Steps to Reproduce

Swap L/R with L2/R2 in settings -->key map. Launch a game (i tested with gba). Restart device, launch it from game switcher.

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Olywa** [comment]
Will have to wait for the developer to comment here.

**Comment by Sichroteph** [comment]
thanks for your feedback. It appears that the custom layout panel is compatible with mainUI only. To avoid any confusion in the future it will be removed so the user has to use retroarch for this purpose.

**Comment by synthead** [comment]
> It appears that the custom layout panel is compatible with mainUI only.

It would be great to learn why this is and support this feature in Onion, too :wink:
