### ISSUE TITLE
[bug] in favourites no images in detail mode (dpad r)

### ISSUE THREAD

**Issue by ac3nl** [OnionUI/Onion#199]
In my favourites list i do see images, however when i press dpad Right, no images are there.

in console list, i do see images, when i press dpad Right

**Comment by Olywa** [comment]
While this is not fixed as such (it's an issue caused by Miyoo's code which we have no source or control over), with Onion V4 there is now a tool in the Tweaks App that will add the missing thumbnails to the infopanel:
 `Apps > Tweaks > Tools > Favorites: Fix thumnails and duplicates`
