### ISSUE TITLE
1. Default key map has L/R and L2/R2 swapped and 2. Universal controls issue when changing key mapping

### ISSUE THREAD

**Issue by Tortugasss** [OnionUI/Onion#20]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

I'm guessing this is not intentional from you guys.

1. Installing onion 3.12.3 has those buttons swapped, which causes GBA's L/R to work with L2/R2 on the device and fast-forward to be on R. Haven't ran tests in other emus. RA controls shows L=L, R=R, R2=fast forward, but they don't behave like that, they are swapped.

2. Piggybacking here to not open another issue, since it's of similar nature:
Universal controls work as intended in onion when you have swapped buttons in "key map", but they they read the swapped values in emulators.
Example: I have swapped L/R and L2/R2 like seen in picture 3 below. When in Onion, Select+L2 lowers brightness. When in RA, Select+L1 lowers brightness instead.

### Steps to Reproduce

1. Install 3.12.3, check settings --> key map. Then launch a GBA game to see how which buttons are L/R

2. Swap L/R and L2/R2 as seen in picture 3 below. Try to lower the brightness. Launch RA (tested in GBA). Try to lower the brightness again.

### Provide any additional context or information that may help us investigate your issue

This is how my key maps look like after installing onion
![1](https://user-images.githubusercontent.com/109543711/179613841-af28e877-8dd9-4080-ac4a-4f611c282d44.jpg)

Demonstration from the wiki on where the lines lead regarding L/R and L2/R2
![2](https://user-images.githubusercontent.com/16885275/178003377-10332587-c44e-46f6-b3cc-315df906a00b.png)

How they should be in key mapping by default and how RA sees them (at least in GBA)
![3](https://user-images.githubusercontent.com/109543711/179613848-9865bf9b-d960-41ea-af88-438cbed576a1.jpg)

**Comment by Olywa** [comment]
OK, re GBA triggers being on L2/R2 yes this is normal, I _think_ it has to do with the RA defaults but I'm sure there are reasons it was kept this way. I believe it's recommended to do any key remapping in the RA menus only (rather than using the setting->key map) so you can have more control at a per system/per game level.

We will see if the developer can comment when he has some time.

**Comment by Sichroteph** [comment]
thanks for your feedback. It appears that the custom layout panel is compatible with mainUI only. To avoid any confusion in the future it will be removed so the user has to use retroarch for this purpose.
