### ISSUE TITLE
Potential Preview Image for Code Theme

### ISSUE THREAD

**Issue by brandish-transfusible** [OnionUI/Onion#222]
Codec Theme does not currently have a preview image. Maybe this screens shot would work. Now 480x360 to match Preview Size.

![MainUI_codec_preview](https://user-images.githubusercontent.com/84584373/171071741-03b64696-691b-4fb4-98e0-5e8ae1785cad.png)

**Comment by Olywa** [comment]
A preview was since added to the theme in [the repository](https://github.com/OnionUI/Themes/blob/main/README.md#custom-themes) (maybe even your one!). 

Thanks.
