### ISSUE TITLE
Oransje Theme appears not to draw Text

### ISSUE THREAD

**Issue by brandish-transfusible** [OnionUI/Onion#223]
![MainUI_Oransjes_no_text](https://user-images.githubusercontent.com/84584373/171070502-c78872c2-af14-4255-81bf-0b735a4e4e41.png)

Text for Menus and A and B button text do not appear to be drawing.
SOLUTION: Text will draw if "hideIconTitle":true in config.json is set to false.

SIDE ASK: Is there a logical mapping of the code path for how the text is drawn, to identify if this is a data error in theme or if an edge case in the theme processing logic?

**Comment by Olywa** [comment]
Looks like this was since fixed. Just verified with Onion v4 and the latest version from the [Themes Repository](https://github.com/OnionUI/Themes/blob/main/README.md#custom-themes). Closing.
