### ISSUE TITLE
overlays don't work

### ISSUE THREAD

**Issue by mcfly90** [OnionUI/Onion#23]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

april lasr update

### Provide a clear and concise description of the issue

When i want add overlay to the gameboy, gbc, gba, game gear games, the files in option overlays don't show, i dont find any frame for gameboy like dmg to simulate a original gameboy

### Steps to Reproduce

in game press select and menu and open retroarch menu, select the overlays option and doesnt work, not show any files

### Provide any additional context or information that may help us investigate your issue

The original firmware on micro sd include when send me the console works fine with the overlays

**Comment by Olywa** [comment]
Overlays have never been supported in Onion unfortunately and this decision was taken for performance reasons along with weighing development effort vs benefit, there are no plans for them to be added at the moment.

Onion is using a custom build of Retroarch which is in part why many of the systems perform better than stock. The sdl-based video drivers do not support overlays by default and it would be a lot of work to enable them. It's more complex than you might imagine to add support for overlays to the custom build and the Onion devs believe that the Miyoo dev team spent significant time adding support for them on the Mini.

If you want to know more you can review the [most recent discussion between the devs](https://discord.com/channels/529983248114122762/931367023588569180/986775660812976178) on discord (it wasn't the first) but I'm afraid it won't change the outcome.

Closing as won't fix but if anything changes in the future I'm sure this feature will be reconsidered.
