### ISSUE TITLE
MAME / MESS subsystems 

### ISSUE THREAD

**Issue by brunobelo** [OnionUI/Onion#27]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Unimportant

### Miyoo Firmware Version

latest

### Provide a clear and concise description of the issue

Hi all. On the last github official onion page I posted a question about MAME / MESS subsystems, but the message was deleted when the repo moved. 

Today I found a way to run them, it was pretty tricky and involved old hardware to compile it but I managed to run CD-i (still need to fix the controls) or AdventureVision (perfectly) on the Miyoo. This improves significantly the amount of devices it can emulate and I had to make my way to make it work. 

So the question is: are you interested on it? I'll probably upload it to reddit miyoo but if it was added to the official onion os it would be great. 

### Steps to Reproduce

Unimportant

### Provide any additional context or information that may help us investigate your issue

Irrelevant

**Comment by Olywa** [comment]
Hi there, While I appreciate you wanting to contribute (it's genuinely welcome and I have no doubt you put a lot of time and effort into figuring this out) this is not the correct way to do so. 

We make very clear the **Issues** tab is for raising issues _only_  when you click the `new issue` button. 

The problem with raising it here is that it will not get enough visibility from other users.
I would ask you to please either raise it on the discord (linked at the `new issue` button) or make a reddit post as you suggest, the team are all active on both and this way you can garner support from other users and the request has a higher likelihood of being included in a future release if there is enough support for it.

Many thanks.
