### ISSUE TITLE
Folders with apostrophes not recognized

### ISSUE THREAD

**Issue by ghackett** [OnionUI/Onion#301]
Rom subfolders that have apostrophes in their names don't get recognized by onionos. Discovered this by dumping all my psx games into subfolders to group the associated bin/cue/m3u files. All the folders show up except the ones with apostrophes (i.e Tony Hawk's Pro Skater or Tom Clancy's Rainbow Six). Dropping the apostrophes from those directories (and deleting the cache db file) resolved the issue. Files with apostrophes are not impacted, just folders.

Using onion is 3.9.1 installed fresh on top of the January official firmware.

**Comment by Olywa** [comment]
Closing this as there has been no update/resolution from Miyoo (I'm not convinced there ever will be).
For now it is at least [documented in our wiki here](https://github.com/OnionUI/Onion/wiki/Emulators#rom-files).
