### ISSUE TITLE
ROM folder for TIC-80 is incorrect

### ISSUE THREAD

**Issue by nightmareci** [OnionUI/Onion#31]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://github.com/OnionUI/Onion/wiki/2.-Emulators-and-Ports#tic-80-

### Description

The ROM folder indicated in the wiki for TIC-80 is incorrect.

### Correction

Change the indicated TIC-80 ROM folder from `tic80` to `TIC`.

**Comment by Olywa** [comment]
Hi there, thanks for reporting this.

Looks like we had it right in the quick ref table at the bottom of the page but did not update the TIC-80 section as you rightly point out. It has been corrected now 👍
