### ISSUE TITLE
Fix audio option inside settings

### ISSUE THREAD

**Issue by GhsVilela** [OnionUI/Onion#314]

**Comment by ZhuYilin10** [comment]
Hello everyone,

I am very interested in the issue you are discussing, but I don't even know how to run ONScripter on my miyoo mini. Can anyone tell me how to do it? Thank you!

**Comment by ZhuYilin10** [comment]
Hello everyone,

I am very interested in the issue you are discussing, but I don't even know how to run ONScripter on my miyoo mini. Can anyone tell me how to do it? Thank you!
