### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by albgr1979** [OnionUI/Onion#34]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

“Spanish" language does not appear in the language selection menu.

### Steps to Reproduce

Settings-language

### Provide any additional context or information that may help us investigate your issue

Reviewing the file “miyoo\app\lang\es.lang” I have seen that a “,” is missing in the line “106:Native Menu” and when adding it, the Spanish language appears to select it.
The problem is that when you change to another "theme" you have to do the process again to be able to select the Spanish language again.

**Comment by Sichroteph** [comment]
Thanks a lot for your report, it will be fixed on the next version.
