### ISSUE TITLE
Multi-disc games do not load through .m3u on X68000 core

### ISSUE THREAD

**Issue by ilmenit** [OnionUI/Onion#35]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

On X68000 system to load multi-disc games the .m3u file should be used. However when .m3u is started it does not load the game and stays on the black screen, there is also no rumble for disc access so it's not that the game is loading. The single .dim disc games start properly. No multi-disc game starts through .m3u.
It seems there was a bug in older version of px68k that has been fixed: https://github.com/libretro/px68k-libretro/issues/144
Not sure if that's the main reason why the multi-disc games do not load but it may be worth to build the core from the newest sources.

### Steps to Reproduce

1. Create a new .m3u file that has names of the disks, e.g. "Sol-Feace.m3u" with the following lines corresponding to the .dim names:
Sol-Feace (1990)(Wolf Team)(Disk 1 of 3).dim
Sol-Feace (1990)(Wolf Team)(Disk 2 of 3).dim
Sol-Feace (1990)(Wolf Team)(Disk 3 of 3).dim
2. Refresh Roms
3. Launch the game (through Sol-Feace)

### Provide any additional context or information that may help us investigate your issue

I have tried to place the .dim files in current folder and subfolders and make .m3u to point them but nothing worked.

**Comment by Olywa** [comment]
Hi there, would you be able to test with this [recent buildbot core](https://classicmodscloud.com/classic_libretro/nightly/classic_armv7_a7/2022-08-06/so/px68k_libretro.so) to see if it resolves the m3u issues? Rename your existing core (temporarily) and place this one in the same `\RetroArch\.retroarch\cores` location

**Comment by Olywa** [comment]
Great news, glad it helped, will see if we can get the core replaced with this one in the next release.

**Comment by Olywa** [comment]
@Aemiii91 can we replace the current px68k-libretro core with the one I linked above in the next release to resolve this issue please?

**Comment by Aemiii91** [comment]
On it!

**Comment by Aemiii91** [comment]
And done, it will be included in the next release.
