### ISSUE TITLE
TIC-80 does not run at full speed.

### ISSUE THREAD

**Issue by IllustratedMan-code** [OnionUI/Onion#353]
Some games do not run at full speed. Stele and Supernova both appear to run at full speed, but super meat boy demake and Tiny Dungeon run at a snail's pace (about 4x slower than it should). Not sure if it is a quirk of the emulator or not. I tried enabling the threaded video setting, but it didn't seem to help.

**Comment by b-risk** [comment]
Hi, this issue seems to still not be fixed
