### ISSUE TITLE
txt file set to load on boot. Black screen.

### ISSUE THREAD

**Issue by lotech** [OnionUI/Onion#36]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

20220419****

### Provide a clear and concise description of the issue

I accidentally choose test.txt in the GBA rom listing which wouldn't load for obvious reasons - but did load to a black screen. Rebooting had set it to auto boot the test.txt again locking me out of the menu.
I discovered the update file in the root and spotted the line, which I removed and now it starts again.
Test.txt seems to been file listing txt.

### Steps to Reproduce

Open a txt file when in the GBA rom list. Probably occurs on other rom listings.

### Provide any additional context or information that may help us investigate your issue

No more context required.

**Comment by Olywa** [comment]
This is an unfortunate consequence of loading and sending retroarch/the core an unsupported (non-rom) file. 

You can specify non-rom files to not appear in the consoles game list to avoid this happening in future. Taking GBA as the example, if you put your SD card in your PC, go to \Emu\GBA\config.json and open this file with a text editor, then replace the line that reads: 
`"extlist":""`
with: 
`"extlist":"GBA|gba"` 
This will tell Onion to _only_ display games with the specified extensions so .txt or .xml files will no longer show up in your game list. 

You may need to refresh your roms after making the change (highlight the console and press menu button>refresh). You can apply this change to any system but note that the specified extensions are case sensitive (hence having it there twice to cover both caps and lowercase). 

The simplest method of course is just to delete any .txt files from your roms folders.
