### ISSUE TITLE
Build files for RetroArch not in repo

### ISSUE THREAD

**Issue by synthead** [OnionUI/Onion#39]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

n/a

### Miyoo Firmware Version

n/a

### Provide a clear and concise description of the issue

In `README.md`, it states that RetroArch is built from scratch.

https://github.com/OnionUI/Onion#retroarch-rebuilt-from-scratch

However, the sources (or link to appropriate sources) and build scripts are nowhere to be found in this repo.  How does it get built?

### Steps to Reproduce

1. Look at `README.md`
2. Be confused

### Provide any additional context or information that may help us investigate your issue

It would be great to have instructions on how to build everything.  It seems like almost all developer documentation and resources are missing aside from the small helper wrappers in `src/`.

**Comment by Olywa** [comment]
I think you have this info now and see that the repo is going through some major refactoring so this should be naturally resolved shortly. I'm closing the issue but please let me know if you disagree.
