### ISSUE TITLE
Theme image links return 404 when clicked in 3.12.3 release

### ISSUE THREAD

**Issue by synthead** [OnionUI/Onion#41]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

n/a

### Provide a clear and concise description of the issue

Clicking on these themes in [the 3.12.3 release](https://github.com/OnionUI/Onion/releases/tag/20220705) returns a 404:

![image](https://user-images.githubusercontent.com/820984/183278048-d9ca8e72-9002-4b18-ae30-d1fd5a587527.png)

### Steps to Reproduce

1. Click on a theme image in [the 3.12.3 release](https://github.com/OnionUI/Onion/releases/tag/20220705).
2. Observe a 404.

### Provide any additional context or information that may help us investigate your issue

It looks like these links are going to the https://github.com/Sichroteph/Onion repo, a fork of https://github.com/OnionUI/Onion.

**Comment by Aemiii91** [comment]
Thank you, the links are now removed. Themes are found at https://github.com/OnionUI/Themes.
