### ISSUE TITLE
Bold font in list

### ISSUE THREAD

**Issue by mbgroot** [OnionUI/Onion#42]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

20220419

### Provide a clear and concise description of the issue

I'm doing a custom theme. I use a custom font. In the list, the font is rendered in bold style. But I do not specify it in the configuration: 
```
    "list":{
        "font":"zxfont.ttf",
        "size":45,
        "color":"#000000",
        "selectedcolor":"#FFFFFF"
    }
```
And with the selected item a shadow is added, you get a double-bold style.
![image](https://user-images.githubusercontent.com/7091348/183299594-3e10720e-21df-4f7d-a2b8-865000cf6093.png)

### Steps to Reproduce

Open the configuration menu.

### Provide any additional context or information that may help us investigate your issue

Maybe it's not a bug, but just a lack of documentation. But if I don't explicitly specify the use of bold in the config, it should be a normal font.

**Comment by Aemiii91** [comment]
This is MainUI specific, which is the menu program by Miyoo (closed source, out of our hands).
