### ISSUE TITLE
SNES9x2005 > Superfaust

### ISSUE THREAD

**Issue by rogalian** [OnionUI/Onion#465]

**Comment by WingofaGriffin** [comment]
Reviving this issue to see how things may have changed in the last few months. Assuming the spreadsheet you are referring to is the [Batocera](https://batocera.org/compatibility.php) one shared in the discord, it looks like Supafaust is no longer tested, and isn't advertised on libretro docs.

Snes9x seems to work fine, though I know Snes9x-2010 (previously Snes9x-Next) has some ARM optimization from libretro. Any thoughts?
