### ISSUE TITLE
Flag ".noBatteryWarning"  to disable battery warning

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#57]
Flag ".noBatteryWarning"  to disable battery warning ([from this fork](https://github.com/OnionUI/Onion/commit/d63e11a2b2394b54d08ce0feac4cfe2b9a141a77))

**Comment by Aemiii91** [comment]
This flag is actually deprecated now (But still supported). If you set `Tweaks` > `User interface` > `Low battery warning` to `Off`, it will the same effect.
