### ISSUE TITLE
The display problem of Chinese

### ISSUE THREAD

**Issue by 446599** [OnionUI/Onion#599]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3

### Miyoo Firmware Version

0419

### Provide a clear and concise description of the issue

After selecting Chinese in the settings, some text in the home menu cannot be displayed.
Some fonts are not compatible with Chinese, which prevents menus and game titles from being displayed.
The tweaks app not supports language except English.

### Steps to Reproduce

Select Chinese
Back to the home menu

### Provide any additional context or information that may help us investigate your issue

I find that the main reason which leads the home menu display error is the file “ch.lang”
I had tried to repair it and it works well.
[ch.zip](https://github.com/OnionUI/Onion/files/9925777/ch.zip)
And if possible, use Chinese compatible fonts，thanks

**Comment by Aemiii91** [comment]
Fixed in:
- #971 / 30868210db44d5a6a0a13a5a9d27c35610cfbf13
