### ISSUE TITLE
Menu button double click action from RA

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#60]
Double click from MainUI already launch the last game, so what action from RA ?

 Switch between the 2 last game played like an alt-tab ?

**Comment by Aemiii91** [comment]
As part of implementing Tweaks, I'm also implementing "double-press" menu button action. Double-press from MainUI should skip the GameSwitcher and just resume last game immediately. When in-game, double-press will be "Quick switch" to second last game played. This will of course be customizable via Tweaks.

**Comment by schmurtzm** [comment]
Fully working in dev v4,  🎉 .
I close.
