### ISSUE TITLE
Sound muted in ScummVM

### ISSUE THREAD

**Issue by iconoclusterdotexe** [OnionUI/Onion#604]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1dev-alpha

### Miyoo Firmware Version

April 2022

### Provide a clear and concise description of the issue

No sound with every ScummVM game.

### Steps to Reproduce

- Run a ScummVM game

### Provide any additional context or information that may help us investigate your issue

On /Emu/SCUMMVM/launch.sh file there are these lines (20, 21, 27):

```
killall audioserver
killall audioserver.mod

/mnt/SDCARD/miyoo/app/audioserver &
```

By removing or comment these lines, the sound works.

**Comment by schmurtzm** [comment]
> Just a question: Why you restart the audio server after launching retroarch and its core? Personally i find that a bit senseless. If you want to save some ram, isn't better to restart it immediately after killing audioserver and audioserver.mod?

The audio server use about 30MB of ram and scummvm core is big so it's nice to have the most of ram possible.
We don't need it during scummvm is running but just after it is required by MainUI.

About your main problem, I can't reproduce, can you update again with the last alpha version ?

**Comment by schmurtzm** [comment]
> > About your main problem, I can't reproduce, can you update again with the last alpha version ?
> 
> Tried the latest one. Same issue :\


Can you try to boot without SD card and set audio fix in paramters ?
Also check your bios version ? 
Try fresh install ?

**Comment by schmurtzm** [comment]
Is there a speaker in your Miyoo Mini ? 😅
I don’t have more ideas 🤔, it will require more feedback 🤷‍♂️

**Comment by Olywa** [comment]
@iconoclusterdotexe can you add a complete copy of your scummvm.ini and launch.sh here please?

**Comment by Aemiii91** [comment]
Closing as this is now stale. ScummVM has also been updated since.
