### ISSUE TITLE
No cover art when saving "search" results to favourites.

### ISSUE THREAD

**Issue by loggio** [OnionUI/Onion#605]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Latest

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

When you use the search app and search for a game and then push select, add to favourite.

Go to favourites, the game boxart is missing.
Boxart only works if you add a game from its system menu.

### Steps to Reproduce

Search "mario"
Add Nes - super mario to favourites.
Go to favourites.
game is listed but thumbnail missing.

Then,
Go to "games"
Go to "nes"
Locate "super mario"
Add the game to favorites

Thumbnail is shown.

### Provide any additional context or information that may help us investigate your issue

Try it

**Comment by Aemiii91** [comment]
This is a known bug which we can't get around at the moment. There's a tool in Tweaks for fixing it, run "Favorites: Fix thumbnails and duplicates" when you've added a game to favorites.
