### ISSUE TITLE
No Ports in the Alpha version

### ISSUE THREAD

**Issue by bloodykean** [OnionUI/Onion#612]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1dev-alpha4

### Miyoo Firmware Version

April 2022

### Provide a clear and concise description of the issue

There are no Ports on the Dev version. Why?

### Steps to Reproduce

Package Manager - No Ports.

### Provide any additional context or information that may help us investigate your issue

No Ports.

**Comment by Olywa** [comment]
The main purpose of the alpha releases is to prove out other functionality and changes.
Improvements are in progress for ports and they will be included in the Beta (and ultimately 4.1).
