### ISSUE TITLE
Legend Of Legaia Battle Screen Stuck

### ISSUE THREAD

**Issue by raieyan** [OnionUI/Onion#616]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

20220419

### Provide a clear and concise description of the issue

when encountering battles the screen constantly rotates when using item,Spirit or Meta and framerate drops significantly.

### Steps to Reproduce

when u first load in the new game after some dialog u will need to train and use the Healing Leaf Item the framerate drops and the screen constantly rotates and gets stuck ..even if u have a save file its the same if u get into any battles

### Provide any additional context or information that may help us investigate your issue

The issue leads to the game being unplayable and have tested it with mini ui it drops frames during this scene but no issue where it constantly rotates and gets stuck after using an item,spirit or meta

**Comment by Olywa** [comment]
Hi there, this seems to be a [known issue with this game](https://www.reddit.com/r/PlaystationClassic/comments/bg4ksl/legend_of_legaia_frame_rate_issue/) and the PSX core (PCSX Rearmed). 

There is not really anything that the Onion team can do with core issues this extreme you might try:
Increasing the CPU clock speed in the retroarch settings (as noted in one of the replies on that link).

- Disable any performance impacting features in the Retroarch settings if you are using them (like FF, RW, and enhanced resolution).
- Use CHD rom files and the `PSXONPSP660.bin` bios which can allegedly result in slightly better performance.
- Try the game with the Standalone PCSX emulator available in Onions Expert section. 

Hopefully something there helps. Beyond this your only option is to log an issue with the core developer and hope that they look into it: https://github.com/notaz/pcsx_rearmed/issues
