### ISSUE TITLE
SNES aspect ratio bug

### ISSUE THREAD

**Issue by MushGuyDS** [OnionUI/Onion#618]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

I think this is related to porting the SNES cores to Miyoo Mini since that issue isn't seen in other platforms, but when I start Donkey Kong Country, after the Nintendo logo appears, the screen is squished to half the vertical resolution, but then it changes back to normal after Cranky Kong appears on screen.

### Steps to Reproduce

Turn Integer Scale and Keep Aspect Ratio on in Retroarch (this is to display the games in pixel-perfect 8:7 ratio since the cores don't have the option), then run Donkey Kong Country on either SNES9X (also tried on 2005+) or Beetle Supafaust.

### Provide any additional context or information that may help us investigate your issue

A workaround for SNES9X (2005+ doesn't have it) is to disable Hi-Res Mode or setting Hi-Res Blending to Merge in order to force 8:7 when the Nintendo logo appears. On Supafaust, this bug happens with Donkey Kong Country, but not with Kirby's Dream Land 3, oddly enough.

**Comment by Aemiii91** [comment]
This is just an issue with our video driver combined with the core. It's not something we can fix at the moment.
