### ISSUE TITLE
Migrate emulators from "expert view" to consoles section

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#62]
[Private dev discussion about it](https://discord.com/channels/@me/996705786493407332/1006973916293636286)

Initially Miyoo made these tabs to separate the standalones from the RetroArch cores
it's nice to have the confirmed vs. experimental cores separated, They will still be separated in the installer
is there anything valuable in the expert view now that the ports are gone ? 
Well, some users are using different cores for the same system, so they would want the split (ex spGP in Consoles/Games and mGBA in Expert)

**Comment by Aemiii91** [comment]
I think our current setup is sufficient. Expert is for experimental and duplicate systems.
