### ISSUE TITLE
edit runtime.sh to add activity tracker exception for "Collection Switcher"

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#649]

**Comment by Aemiii91** [comment]
Already done: https://github.com/OnionUI/Onion/pull/623/files#diff-d4c880409fa3390f8eb4c351c55b29767d309eea10ed79d9d206eee760f51c3c

**Comment by schmurtzm** [comment]
Awesome thanks, I' test test tonight 😉
