### ISSUE TITLE
GLO - Game List Options - Features and To Do

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#656]
GLO contains game/rom specific options:

- [x] - Reset game
- [x] - Change game core
- [x] - Open manual (new)

It also contains list specific options:

- [x] - Filter list
- [x] - Refresh roms
- [x] - run random game

And system shortcuts:

- [x] - Set time

Custom users options : 
- [x] - possibility to add your own script

----------------------------------------------
Functionalities proposed by TheDewd :

- [ ] - Go to top
- [ ] - Toggle filenames
- [ ] - Toggle box art preview
----------------------------------------------

- [ ] - Documentation / Wiki

**Comment by JakiShen** [comment]
Add a Gamelist.xml file generator as well
