### ISSUE TITLE
Theme switches back to default theme after turning on from being shut down

### ISSUE THREAD

**Issue by zoneabus** [OnionUI/Onion#659]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202212160314

### Provide a clear and concise description of the issue

Whenever I switch the theme then turn the system off and then on when selecting shutdown on the settings menu or holding the power off button, the theme reverts back to its default one. 

### Steps to Reproduce

Change the theme, then power the system off via the settings menu or power button. Turn the system back on

### Provide any additional context or information that may help us investigate your issue

This been an ongoing issue ever since I ordered from keepretro on December 26 and received it on January 7. This happens no matter what theme I pick as well. When it boots up, 99 percent of the time the text under each menu tile(?) is missing as well.

**Comment by Aemiii91** [comment]
This a firmware issue, read this: https://www.reddit.com/r/MiyooMini/comments/104qbak/community_firmware_patch_for_new_devices/
