### ISSUE TITLE
GBC/Gambatte Core not showing GameSwitcher

### ISSUE THREAD

**Issue by sectune** [OnionUI/Onion#664]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

When launching a GB/GBC game using gambatte core (in my example Pokémon Pinball or Legend of Zelda) the GameSwitcher hotkey (default mapping, 1x press) has no function. The vibration upon key press of the hotkey is there, then nothing. None of the 1x/2x/hold presses are properly registered (ignored). Workaround I found: enter Retroarch via the select+hot key combination and “quit retroarch”, then upon the game Switcher is showing up. This problem does not persist with other cores I tested and seems to be related to GBC/Gambatte.

### Steps to Reproduce

Launch a GB or GBC Game, press hotkey for GameSwitcher

### Provide any additional context or information that may help us investigate your issue

No issue with other cores

**Comment by jonayat** [comment]
I am facing exact same issue with Mame roms (Arcade)
