### ISSUE TITLE
AdobeBlank.ttc crashes Tweaks setting and Gameswitcher

### ISSUE THREAD

**Issue by Tsjoep** [OnionUI/Onion#666]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202212240121

### Provide a clear and concise description of the issue

When making a custom theme, if you change the font for "hint" to AdobeBlank.ttc, you won't be able to access the Tweaks setting and the Gameswitcher. Changing themes seems to fix the problem until you switch back.

### Steps to Reproduce

1. Download a theme (template)
2. Edit the config.json file
3. Under "hint", change the font to AdobeBlank.ttc and save
4. (Make sure you have the font linked somewhere :p)
5. Import the theme to your device
6. Try accessing the Tweaks setting and/or the Gameswitcher

### Provide any additional context or information that may help us investigate your issue

The same problem is described on a reddit post here: https://www.reddit.com/r/MiyooMini/comments/yq32lb/onionos_tweaks_and_game_switcher_stopped_working/

UPDATE: this also seems to disable bootScreen.png. Changing the "hints" font from AdobeBlank.ttc to another one fixes it again.

**Comment by Aemiii91** [comment]
Fixed in  4.3.1
