### ISSUE TITLE
Wrong context menu background in game list

### ISSUE THREAD

**Issue by Tsjoep** [OnionUI/Onion#667]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202212240121

### Provide a clear and concise description of the issue

When you're in the games list in _games>[any console]_ and bring up the context menu you will see three items listed: Launch, Add to favorites and Delete. The background in this context menu is wrong, Onion is displaying _bg-pop-menu-2.png_ which is for 2 context menu items, instead of _bg-pop-menu-3.png_ which is used for 3 context items. This is shown correctly in the favorites list context menu for example.

### Steps to Reproduce

1. Go to games
2. Press any console
3. When on the games list, press SELECT
4. You'll see the context menu is cramped, thus not the right one
(5. Check the favorites list context menu for the right background)

### Provide any additional context or information that may help us investigate your issue

👾

**Comment by Aemiii91** [comment]
We are aware of this inconsistency. Unfortunately it's not something we can do anything about, since it's an error of MainUI - the closed source menu program by miyoo.
