### ISSUE TITLE
Hide ._ files when refreshing roms

### ISSUE THREAD

**Issue by romain-bourgois** [OnionUI/Onion#675]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202212240121

### Provide a clear and concise description of the issue

**Context**
Mac users who copy roms on their micro sd end up with ._ hidden files that are displayed in the list of roms on the miyoo.
As a result, this duplicates the whole list of roms, and displays hundreds of useless entries in the game library.

A reddit thread started on this, and _advanced_ users currently remove those files manually before each micro sd ejection
https://www.reddit.com/r/SBCGaming/comments/z8du3l/how_do_i_get_rid_of_these_error_files_i_use_a_mac/
![image](https://user-images.githubusercontent.com/679351/215389231-e5e095c5-c65b-40f0-be0f-632f35651d3b.png)

**Proposals**
_Option 1: hide files_
Hide those files in the library list, and prevent them from being searchable.

_Option 2: delete files_
Delete those files when refreshing the rom list

**QA**
- Mac user deposit roms in his micro sd
- insert micro sd in miyoo
- refresh roms
- no ._ files are displayed

### Steps to Reproduce

- Mac user deposit roms in his micro sd
- insert micro sd in miyoo
- refresh roms

### Provide any additional context or information that may help us investigate your issue

Those ._ are supposed to be metadata created for each file copied on the usb card by macOS.

**Comment by Aemiii91** [comment]
We are already very aware of this issue. It's a problem with miyoo's menu program, MainUI, which is closed source. There's a tool in Apps -> Tweaks -> Tools to remove them.
