### ISSUE TITLE
Gameswitcher Corruption

### ISSUE THREAD

**Issue by jackiemoonsoon** [OnionUI/Onion#678]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

1224

### Provide a clear and concise description of the issue

Unfortunately I have since resolved the issue by deleting all my game save and states data. I also have updated to the latest 202301041337 firmware. The gameswitcher app had randomly become corrupted. I say this because all the game lists (in the Games menu) would show zero games in OnionOS and any other app I'd try to load would just reload the gameswitcher. I tried rebooting and reseating the SD card several times to no avail. If I tried deleting individual games from the gameswitcher list, nothing would actually delete. The only way to resolve was to delete all my save data on the SD card. I am certain my SD card is good. It's a new Samsung microSD Pro card.

### Steps to Reproduce

Unfortunately, the issue occurred at random. My suspicion is it was caused by one of the CPS3 games (like Street Fighter III: 2nd Impact) as they take a significant amount of time to load. Now when I try to load the gameswitcher for these games, it does not work (nothing happens, the unit just vibrates).

### Provide any additional context or information that may help us investigate your issue

n/a

**Comment by Aemiii91** [comment]
Closing this because it should be fine in the latest Onion. Arcade cores not working with GameSwitcher is normal (it's a core issue).
