### ISSUE TITLE
(MMP) DNS - resolution name problem

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#681]
The name resolution is not working on the MMP (Miyoo Mini+)

```
ping retroachievements.org
ping: bad address 'retroachievements.org'
----------------
nslookup retroachievements.org
Server:    192.168.0.1
Address 1: 192.168.0.1
nslookup: can't resolve 'retroachievements.org'
----------------
nslookup retroachievements.org 1.1.1.1
Server:    1.1.1.1
Address 1: 1.1.1.1
nslookup: can't resolve 'retroachievements.org'
----------------
cat /etc/resolv.conf
search local
nameserver 192.168.0.1 
```

**Comment by DarkSil3ncer** [comment]
@schmurtzm I've run into the same issue... Did you just update the firmware from the Miyoo site? If so what firmware version are you running?

**Comment by schmurtzm** [comment]
It is solved since version 20230326.
Which FW version do you have and what type of testing do you do?

**Comment by DarkSil3ncer** [comment]
That makes sense.
The firmware version on my device is 202303021817. 

From a testing perspective I tried to ping www.google.com via the cmd line.

**Comment by schmurtzm** [comment]
So yes you can update the firmware ;)

**Comment by DarkSil3ncer** [comment]
I can confirm that it works. Thanks man. :)

**Comment by schmurtzm** [comment]
A good occasion to close this old issue !
