### ISSUE TITLE
Add new ports to the list

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#69]
add shortcuts
complete the wiki

**Comment by SmileyChris** [comment]
I updated the wiki to include all of the games in 4.0.0 at least (along with images from the repo)

**Comment by Aemiii91** [comment]
I'm very sorry, but we've just removed all the old images, could you maybe upload some art on the wiki page?

**Comment by SmileyChris** [comment]
Lol great timing 🗡️ 
I'll update the wiki images -- but why are the ports going away?

**Comment by Aemiii91** [comment]
We are overhauling the way ports work 😅
