### ISSUE TITLE
PSX Anti-Piracy detection on ROMS

### ISSUE THREAD

**Issue by MrEnglish96** [OnionUI/Onion#691]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.03

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

You'll have to excuse me if this isn't something that Onion could solve, If I am off the plot here please just disregard this and pretend it never happened! :)

I was wondering if anyone could enlighten me on a workaround of anti-piracy policies with some PSX games.  I realise it's in place for this reason but it's a pain as you all can imagine when a game you so desire is unavailable to you. 
My scenario is this,  LMA manager , 2001 & 2002 (football management games) for PSX all have an anti piracy system built in which result in the players abilities consistently reducing making it impossible to play. I've researched and this is actually built into the game if it's not being played on a disc.   

Is it possible for onion to implement some sort of feature in the PSX files which would result in the game itself thinking its being played on a disc rather than a ROM?  Therefore bypassing the dreaded anti-piracy policy -_-

I have only found this on a few games but of course they are the ones I'd like to play the most. 

### Steps to Reproduce

Loading up a PSX Rom on Onion and playing to see anti-piracy features coming into play.  (for example on LMA manager, the reduction in abilities on a daily basis, making it unplayable)  

### Provide any additional context or information that may help us investigate your issue

Nothing further to add, Thanks!

**Comment by Vexnik** [comment]
I'm assuming you are using a European Version of the game in this case. This is not an onion issue, you are missing some file called .sbi. It needs to be placed with the rom .bin & .cue for it to work
