### ISSUE TITLE
clock app : refactoring

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#70]
* added Clock app to the apps Makefile section
* added Clock app sources to the Apps directory to build via toolchain
* removed unused variable 
* added ability to quit on B button
* removed clock app from static dir 
* fixed rotation of date/time
* added fallback to default datetime "01/01/2022" when year is 1970
* added datetime hint
* refactoring clock app

**Comment by introkun** [comment]
Will be fixed by #51

**Comment by introkun** [comment]
Ready for review again

**Comment by introkun** [comment]
merged
