### ISSUE TITLE
Add m3u support to MSX in Config.JSON extlist

### ISSUE THREAD

**Issue by lucke** [OnionUI/Onion#702]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.4

### Miyoo Firmware Version

202301041337

### Provide a clear and concise description of the issue

The MSX emulator (blueMSX) supports m3u. However, in the config.json in the /Emu/MSX directory, m3u and M3U are missing in the "extlist" parameters.

I've added it manually and m3u (multi dsk games) work perfectly, so I believe it's a bug that this extension is not in the list (since it is indeed supported by the emulator).

### Steps to Reproduce

Add a m3u file into the MSX folder, refresh game list, m3u file does not appear.

### Provide any additional context or information that may help us investigate your issue

It's fixed by adding m3u and M3U into the extlist of the config.json.

Unfortunatelly I don't have enough knowledge to do a PR, hence I report it as an issue.

Thanks for your great work!

**Comment by Aemiii91** [comment]
Done ✅

Thanks for reporting it!
