### ISSUE TITLE
Menu Button Doesn't work in Arcade

### ISSUE THREAD

**Issue by DrBuns3n** [OnionUI/Onion#703]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.04

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

The menu button does not bring up either the game switcher or exit to menu in Arcade (Mame) and the only way to exit seems to be to open retroarch and exit through that. Menu button works as expected in all the other systems I have installed.

### Steps to Reproduce

Launch an arcade (mame) game. Single press or long press menu button, neither do anything although long press does cause a rumble.

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Aemiii91** [comment]
It's a known issue with the mame core, it doesn't respond to exit signals - you have to exit via `MENU+SELECT`.
