### ISSUE TITLE
Red border on screen, battery always 0%

### ISSUE THREAD

**Issue by ym2kmobile** [OnionUI/Onion#709]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1

### Miyoo Firmware Version

202302181113

### Provide a clear and concise description of the issue

Both Onion V4.0.4 & Onion V4.1 is having this issue.

I had just received my miyoo mini+ today. Everything is fine. However when i boot it up with my Onion OS sd card, the first screen i see, there is a red border around my screen. The red border stay even playing a game which is very annoying. Also the battery is always showing 0%.

When i use the default sd card that came with the unit, or boot up without any sd card, everything is fine. I have attached 2 photo for your reference. One is boot without any sd card. The other is with Onion OS.

Even tried to do a clean Onion OS installation on my sd card. The moment it get pass the package installation section, the red box appear.

![IMG_6852](https://user-images.githubusercontent.com/127875363/225064676-323dcec9-93c9-428e-9787-09176b4ead84.jpg)

![IMG_6855](https://user-images.githubusercontent.com/127875363/225064730-621525d2-08c8-47ce-996a-c4a099e0b30a.jpg)

### Steps to Reproduce

Just use a sd card with Onion OS installed in it. Pop it in and the issue will be seen. 

### Provide any additional context or information that may help us investigate your issue

Suspect is incompatibility issue with the latest 202302181113 firmware. Also notice in the setting, with stock sd card, there are additional settings available. As seen in below screenshot, there is setting like "Wifi", "Fixes", "Factory Reset".

With Oinon SD card insert, all these settings when missing..

![IMG_6856](https://user-images.githubusercontent.com/127875363/225068554-4dd19527-a705-4df2-badb-82b7418569ed.jpg)

**Comment by Aemiii91** [comment]
Onion is not compatible with Mini+ yet

**Comment by eRaz3r** [comment]
I get the same issue and I don't understand ist. I thought and read that the miyoo mini plus can also run onion OS. Would you please be so kind and explain this to me?

**Comment by Aemiii91** [comment]
@eRaz3r you need V4.2

**Comment by eRaz3r** [comment]
Thank you. After I look into the releases, I find the hint that the other versions are not compatible at this moment. Thank you.
