### ISSUE TITLE
choose the speed (fps) to display battery animation

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#72]
Now we have 24frames for baterry animation.
It could be nice to manage the speed of this animation : need to implement` { "chargingState": { "fps": 12 } } `for theme configs and overrides config

**Comment by Aemiii91** [comment]
I've implemented support for a file `chargingState.json` next to the chargingState images (in line with the *other* chargingState) - the minimum value for frame_delay is right now 40000 (40 ms, roughly 24 fps):
```json
{ "frame_delay": 50000 }
```
