### ISSUE TITLE
GameSwitcher crashes with items outside /Roms/ in certain paths

### ISSUE THREAD

**Issue by ZackBoe** [OnionUI/Onion#720]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1.0

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

I previously had stashed more roms (full SNES library) at the root at `/- More Roms/sfc/rom.zip` and would access these directly through RetroArch. After playing, entries would appear and be accessible in the Game Switcher.

After updating to 4.1, the GameSwitcher no longer starts - a black screen is displayed and no inputs seem to work besides powering off. 

### Steps to Reproduce

- Add rom to new directory outside `/Roms/`
  - Did not repro: `/test/`, `/test dir/`, `/test dir/nested/`, `/test/SFC/`, `/test roms/`, `/test Roms/`, `/What Roms/` 
  - Did repro: `/- More Roms/SFC/`, `/More Roms/SFC/`, `/More Roms/`, `/- test/SFC/`, `/- test/`

- Launch via Apps > RetroArch > Load Content
- Exit RetroArch
- Launch GameSwitcher

### Provide any additional context or information that may help us investigate your issue

Moving this directory and editing `content_history.lpl` to place it in `/Roms/- More Roms/` resolved the issue.

I'm having a rough time trying to determine exactly what paths cause this. It seems certain that a hyphen will, and I thought perhaps paths containing `Roms` would but `/More Roms/` lead to a crash and `/What Roms/` doesn't. It's late and I'm confused ¯\\\_(ツ)_/¯

I'm also not sure, but I believe this is what caused an issue for me when upgrading to 4.1.0: I had previously set the system to boot into GameSwitcher, and after completing the upgrade to 4.1.0 + Package Manager update, the system wouldn't boot past the OnionOS boot screen.

**Comment by igormartimiano** [comment]
Just a heads up that 4.1.1-dev fixed it for me!
