### ISSUE TITLE
gearsystem icons missing

### ISSUE THREAD

**Issue by 7zxkv** [OnionUI/Onion#724]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1.1

### Miyoo Firmware Version

20220419

### Provide a clear and concise description of the issue

Hi again,

You have made an error for the gearsystem icons that do not appear in the EXPERT mode.

Here is the error and the correction.

in:
\RApp\gearsystem_gg\config.json
and
\RApp\gearsystem_ms\config.json

you have entered:

"icon":".../.../Icons/Default/rapp/gearsystem.png",
"iconsel":"../../Icons/Default/rapp/gearsystem.png",

instead of :

"icon":"../../Icons/Default/rapp/gearsystem_gg.png",
"iconsel":"../../Icons/Default/rapp/gearsystem_gg.png",

and

"icon":"../../Icons/Default/rapp/gearsystem_ms.png",
"iconsel":"../../Icons/Default/rapp/gearsystem_ms.png",

### Steps to Reproduce

.

### Provide any additional context or information that may help us investigate your issue

.

**Comment by Aemiii91** [comment]
Thanks! I'll get it sorted out.
