### ISSUE TITLE
Blank screen when trying to quit RetroArch in 4.2 Beta

### ISSUE THREAD

**Issue by dreams897** [OnionUI/Onion#748]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0 Beta

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

I am using regular Miyoo (not Plus) with 4.2 Beta version and I have an issue when I quit RetroArch I get a blank screen. I basically can't successfully quit without holding down the power button or removing the battery, there is no way to get back to any other menu or display without rebooting. I have tried with achievements and other irrelevant settings turned off and nothing changed. Resetting RetroArch didn't fix anything and this happened with a clean install

### Steps to Reproduce

Launch game either from game list or by launching RetroArch and selecting core/game,
Games run fine but when quitting I get a blank screen and no way to exit without powering down

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Aemiii91** [comment]
Shouldn't be an issue anymore. Feel free to reopen if the issue persists on the latest release.
