### ISSUE TITLE
Wi-Fi icon overlaps battery information when connected

### ISSUE THREAD

**Issue by GSMarafon** [OnionUI/Onion#749]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4,2 (Beta)

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

If you are connected to Wi-Fi, the connection strength icon overlaps the battery information shown on the UI.

### Steps to Reproduce

1) Connect into a valid Wi-Fi hotspot
2) Return to main menu of OnionOS

### Provide any additional context or information that may help us investigate your issue

Here's a image of the issue using the default theme used in OnionOS:

![image](https://user-images.githubusercontent.com/368513/230710855-afea173b-b2dd-4337-81b8-85b9f2906ab6.png)

**Comment by Aemiii91** [comment]
This is included in the release notes under "known bugs". We don't need an issue for it.
