### ISSUE TITLE
Overlays often create strange effects in the GS

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#767]
![Image](https://user-images.githubusercontent.com/7110113/231532072-c6ecfa60-bf6f-4c0b-adf3-bd28926cfa1e.png)

There is an alternative way to make screenshots that I had proposed in the past which is to use the screenshot from RA save state.
The overlay is not displayed but the screenshot is perfect.

However the resolution depend of the core.

May be the rotozoom lib was here for that ?

(Vsync enabling doesn't change this behavior.)

**Comment by gricardo93** [comment]
Yes. All my GS previews are like this image or worse. It would be a great improvement if it can be fixed. I also noticed that the savestate preview are perfect.

**Comment by saskwatch** [comment]
This is really prevalent with the gamebatte core.

**Comment by Aemiii91** [comment]
Fixed with https://github.com/OnionUI/Onion/pull/1011/commits/35bf2426953deaf612a10267644a73d81e08a1d2
