### ISSUE TITLE
Aspect ratio shortcut : behavior improvement

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#774]
Thanks to Eggs we have a shortcut to switch aspect ratio quickly : 
[video_driver_apply_state_changes](https://github.com/OnionUI/RetroArch/blob/068241784fcf0ff3da4b33b8fe92bf5736040d74/retroarch.c#L3685)

Requested improvements : 

- The change of the ratio require a manual core override to be saved. May be an automatic save could be nice.
- A notification (RETRO_MESSAGE_TYPE_STATUS) could be interesting to know which is the current ratio setting (the 4 possibilities are exposed in this [official Retroarch feature request](https://github.com/libretro/RetroArch/issues/14495))

**Comment by 0neblock** [comment]
@schmurtzm I have a PR in retroarch here that does point #2: https://github.com/OnionUI/RetroArch/pull/7

**Comment by schmurtzm** [comment]
Nice ! Thanks, I'll take a look !

**Comment by Aemiii91** [comment]
Done in:
- #968
