### ISSUE TITLE
Retroarch settings not being saved after saving overrides for individual games

### ISSUE THREAD

**Issue by dreams897** [OnionUI/Onion#778]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1.4

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

After saving overrides for individual games in Retroarch they are often not loaded correctly when re-launching the game and are usually forgotten entirely if you have previously saved settings for those games.

### Steps to Reproduce

Make some changes to a game's settings in Retroarch, go to overrides menu and save for game, core, etc., launch game and settings may not be applied, particularly if they have been updated from previously saved settings

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Aemiii91** [comment]
Will get fixed when 08a3f7d is released (RetroArch updated to 1.15.0)
