### ISSUE TITLE
[wiki] Links to standalone ports are dead

### ISSUE THREAD

**Issue by anzz1** [OnionUI/Onion#783]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://github.com/OnionUI/Onion/wiki/Third-Party-Apps#additional-ports-and-standalones

### Description

All the links to standalone ports are 404

### Correction

404 -> 200

**Comment by Aemiii91** [comment]
Deleted ✅
