### ISSUE TITLE
mGBA unable to run final fantasy 6 lag

### ISSUE THREAD

**Issue by r00t8ug83** [OnionUI/Onion#803]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

V4.2.0.2-beta-4E7C2DB

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

mGBA unable to play FF6 games feel very lag...  fps drop and audio problem

### Steps to Reproduce

Launch a FF6 game starting game around 10min you will see the performance running very bad.

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Olywa** [comment]
Not every game will run perfectly on the default core but it does have the widest compatibility. 
If you have enabled rewind in the Retroarch settings then definitely disable that as it will impact emulation performance due the limited resources of the Miyoo Mini and Plus. 

Alternatively, you can try the game with the gpSP core by switching the core for only that game using the Game List Options (GLO). To do this, highlight the game in your game list and press Y to evoke the GLO menu. Note that if changing the core you will also need to move (or copy) and rename your save file if you wish to carry your progress over. mGBA uses romname.srm and gpSP uses romname.sav (you can just rename the extension from one to the other). 

Save file locations are noted in the FAQ section of the wiki. 
https://github.com/OnionUI/Onion/wiki/Frequently-Asked-Questions-%28FAQ%29#how-do-i-add-game-saves
