### ISSUE TITLE
Wifi Option Missing in Setting Menu After Swapping SD Card From MM+ to Regualr Mini

### ISSUE THREAD

**Issue by Blitzpwnage** [OnionUI/Onion#805]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Latest build v4.2 beta dev build

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

My WIFI was working fine and was connecting to my network. Then I took my SD card from my Miyoo Mini Plus and put it in my Regular Mini. I then took that same card and put it back in the Mini Plus and the Wi-Fi option is completely missing. I am thinking this has something to do with the OS recognizing the system and hiding the option but then not picking the system back up again once it’s plugged into the Mini Plus with WI-FI. Not sure if this is a config setting I can change somewhere. 

### Steps to Reproduce

1. Take your SD card that is in your Mini Plus and put it in your Miyoo mini regular and boot up the mini regular
2. Next take that same card and put it back into the mini plus.
3. Wi-Fi will now be hidden in the setting menu

### Provide any additional context or information that may help us investigate your issue

Nothing more to add

**Comment by Olywa** [comment]
Definitely sounds like a bug, we will look into it. 
Do you have your stock SD separately? If so, have your tried with that to see if the setting is restored (or even booting with no SD inserted).

Thinking about it, it may just be a theme issue, can you also try swapping themes in Onion ?

**Comment by Aemiii91** [comment]
Something is going wrong with the device check at boot. Try reinstalling Onion.
