### ISSUE TITLE
GBAOffsett video filter not aligning to top edge

### ISSUE THREAD

**Issue by benjaminabner** [OnionUI/Onion#837]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0-beta

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

When using the GBAOffset filter, the filter shifts the image upwards but does not align to the top properly (a few pixels of blank black space is left on the top). This leads to a few pixels being cut off at the bottom when using an overlay.

### Steps to Reproduce

1. Video Filter = GBAOffset
2. On-Screen Overlay = GB_3x_BorderOnly
3. Toggle through screen sizes using Menu + Start

### Provide any additional context or information that may help us investigate your issue

Filter file should be adjusted to compensate for top gap.

**Comment by dreams897** [comment]
I noticed you may be using the wrong on-screen overlay, if you are using GB_3X and not GBA_3X. I recommend downloading the presets on this page if you haven't already: https://github.com/OnionUI/Onion/discussions/708

I use GBA offset filter/on-screen overlay and I have not noticed any alignment issues
