### ISSUE TITLE
Battery percentage is always 0%

### ISSUE THREAD

**Issue by Frusco** [OnionUI/Onion#838]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.1.4

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

During and after the installation of Onion OS battery percentage is always 0%
Stock OS:
![02](https://github.com/OnionUI/Onion/assets/24657635/c7ab9e34-08c1-4fb9-b086-b33ee337c239)
![01](https://github.com/OnionUI/Onion/assets/24657635/0dfa4201-fc1c-47b6-b520-47697b223570)
Onion OS 4.1.4:
![05](https://github.com/OnionUI/Onion/assets/24657635/98bc0960-1eb8-4891-ba1c-6b30838b922a)
![06](https://github.com/OnionUI/Onion/assets/24657635/64a1d6b9-90ef-4c23-b47f-71d44c4083e9)
![07](https://github.com/OnionUI/Onion/assets/24657635/02e5e350-a7fc-4a1e-93c6-a338c47ab2e9)

The problem persist even when charging
![08](https://github.com/OnionUI/Onion/assets/24657635/f1ef1d17-96cc-4384-a007-ff0afc4ae7d5)

### Steps to Reproduce

Just following installation guide, bug appears at "2/2 installing Retroarch... 100%"
![03](https://github.com/OnionUI/Onion/assets/24657635/9a2268ff-fae8-4c9b-be05-0c0ef6adf681)
![04](https://github.com/OnionUI/Onion/assets/24657635/d6c8769c-513c-4361-98a8-aef71859bf79)
![05](https://github.com/OnionUI/Onion/assets/24657635/0ecbd7bd-36a2-47bb-9d68-20bc5cfae1e7)
![06](https://github.com/OnionUI/Onion/assets/24657635/bbc06447-898b-43dd-85a8-df0a76bb473e)
![07](https://github.com/OnionUI/Onion/assets/24657635/b33fc3e1-2fa3-4d79-8120-64383ae31a3a)

### Provide any additional context or information that may help us investigate your issue

Same SD card on Miyoo mini fw: 202204190828, all work as expected.
![09](https://github.com/OnionUI/Onion/assets/24657635/265b1299-455f-4d26-989f-dbb02ce93de3)

**Comment by Frusco** [comment]
Wrong OS version

**Comment by eRaz3r** [comment]
Could you I get the same issue and I dont't understand the "Wrong OS VErsion". Would you please be so kind and explain this to me?
