### ISSUE TITLE
lemiyoo.cn/upgrade link is dead

### ISSUE THREAD

**Issue by mbledkowski** [OnionUI/Onion#840]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://github.com/OnionUI/Onion/wiki/Installation

### Description

lemiyoo.cn/upgrade link in firmware upgrade section is dead.

### Correction

I have no idea where to find the latest firmware, but there is some available at lomiyoo.com

**Comment by Aemiii91** [comment]
We're not linking to lemiyoo.cn ??

**Comment by Aemiii91** [comment]
The installation guide has no dead links.

**Comment by mbledkowski** [comment]
![image](https://github.com/OnionUI/Onion/assets/23295125/812067d7-a977-42e7-86d6-41cb11d62a2c)
![image](https://github.com/OnionUI/Onion/assets/23295125/9c66dfc3-2ec9-4aba-bf8b-3b47089255a2)
@Aemiii91 We're linking !!

**Comment by Aemiii91** [comment]
Then you should have stated that the "firmware upgrade guide" we're linking to is out-dated.

**Comment by Aemiii91** [comment]
OK, fixed (https://github.com/OnionUI/Onion/wiki/Installation/_compare/791cfa35427136e50526886be3415a9edf72eb67)
