### ISSUE TITLE
OTA UPDATE on Dev v4.2.0 beta 3 tells that there is the same update ready to download

### ISSUE THREAD

**Issue by Amiga500** [OnionUI/Onion#843]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion-v4.2.0.3-beta-dev-d937d44

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

OTA UPDATE on Dev v4.2.0 beta 3 tells that there is the same update ready to download

### Steps to Reproduce

with 4.2.0.3 update installed, go into Apps -> Onion OTA update and wait. You'll see the same release to download (d937d44).

### Provide any additional context or information that may help us investigate your issue

![beta3](https://github.com/OnionUI/Onion/assets/16525337/07b9a23f-1fc6-42eb-b6fb-f8ffc0de924d)

**Comment by Aemiii91** [comment]
Fixed
