### ISSUE TITLE
device softlocking when resetting to defaults in retroarch config file

### ISSUE THREAD

**Issue by puggersbepugging** [OnionUI/Onion#873]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

420 beta dev

### Miyoo Firmware Version

latest

### Provide a clear and concise description of the issue

whenever i press 'reset to defaults' in configuration file of retroarch, the device softlocks and i cant do anything unless i turn it off and back on. text also turns green?

### Steps to Reproduce

open retroarch, go to the settings tab where you save/load configuration file, press 'reset to defaults'

### Provide any additional context or information that may help us investigate your issue

the text at the bottom will keep scrolling but my device wont exit out of retroarch unless i reboot

**Comment by Aemiii91** [comment]
Yes. Messing with RetroArch settings is not a bug in Onion. When you reset inside RA, you reset to **RetroArch defaults** - meaning you will lose all Onion related settings (key mapping for example). We have a special reset function in Apps -> Tweaks for resetting to **Onion defaults**.
