### ISSUE TITLE
no connection wifi if the password key contains the & symbol

### ISSUE THREAD

**Issue by ahahahaah** [OnionUI/Onion#882]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

 Onion-v4.2.0-beta-dev-072c73c

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

the wifi connection is impossible if the password key contains the & symbol

### Steps to Reproduce

try to connect to wifi with a password key containing the & symbol

### Provide any additional context or information that may help us investigate your issue

no other additional context or information for this issue...

**Comment by XK9274** [comment]
Have you tried any of these?:

https://github.com/OnionUI/Onion/issues/780
https://github.com/OnionUI/Onion/issues/781#issuecomment-1511717316
https://www.reddit.com/r/MiyooMini/comments/13rsdxd/better_wifi_app_vnc_server_mm_onionos/

**Comment by ahahahaah** [comment]
ok the issue is known, i will see which way to choose
thanks

**Comment by XK9274** [comment]
Wiki page updated: [here](https://github.com/OnionUI/Onion/wiki/Frequently-Asked-Questions-%28FAQ%29#my-wifi-wont-connect-as-it-contains-special-characters-what-do-i-do)

I've added a new entry, let me know if you need further guidance so I can assist & update the wiki so others can benefit.
