### ISSUE TITLE
No game sounds anymore and menu button lost the functions

### ISSUE THREAD

**Issue by ahahahaah** [OnionUI/Onion#883]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion-v4.2.0-beta-dev-072c73c

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

after installing the last release, the menu button doesnt lead to the menu anymore, it only opens the gameswitcher and exits...

2nd issue
no sound in games, i have the sound only in the home menu and music player. nothing in the games

### Steps to Reproduce

after installing the last release, the menu button doesnt lead to the menu anymore, it only opens the gameswitcher and exits...

2nd issue
no sound in games, i have the sound only in the home menu and music player. nothing in the games

### Provide any additional context or information that may help us investigate your issue

nothing special to add

**Comment by antipasta** [comment]
i also have no sound in games after upgrading to the lates tbeta

**Comment by ahahahaah** [comment]
> i also have no sound in games after upgrading to the lates tbeta

do you know how to download the older releases?

**Comment by antipasta** [comment]
Here is a link to a previous beta that I found on reddit. I downgraded to it and sound is working again for me: https://drive.google.com/file/d/15QA4TaUYP0MicLklG2eLB-1I4KXWQlLQ/view

**Comment by ahahahaah** [comment]
thank you, is there a "normal" way to found the files?

**Comment by antipasta** [comment]
typically they would be here https://github.com/OnionUI/Onion/tags , but i think they delete old tagged releases of the beta, since this particular one isn't here.

**Comment by ahahahaah** [comment]
lol it was so simple!!
thanks

**Comment by ahahahaah** [comment]
all the 4.2 links lead to the same file lol
anyway 
thanks for the google drive

**Comment by HydroReaper666** [comment]
Happened to me to but I just went into retroarch audio settings and changed the setting to sdl
