### ISSUE TITLE
Volume bar flicker

### ISSUE THREAD

**Issue by Refaze** [OnionUI/Onion#886]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion beta 4.2 (latest)

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

I am hoping this isn't my unit.  Screen looks beautiful but when the volume is engaged the volume bar has.a slight flicker almost like it's buggy.  Also when playing the Streets Of Rage remake the volume bar glitches completely out
Both extremely minor,  you folks are doing a great job!  I just want to make sure there is nothing wrong with my unit.

### Steps to Reproduce

Adjust the volume rocker in and out of games.

### Provide any additional context or information that may help us investigate your issue

Seems to happen more in game. Using Miyoo Mini Plus.

**Comment by Aemiii91** [comment]
Not a bug. That is the best we can do.

It's worse on some apps/games because they draw to the screen faster/more often. We're already drawing the volume bar as fast as we possibly can.
