### ISSUE TITLE
Cannot recall save states when 1000 save states are present

### ISSUE THREAD

**Issue by synthead** [OnionUI/Onion#890]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

v4.2.0-beta-dev-4c7e2db

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

When 1000 save states are stored for a game, no save states can be recalled.  This was encountered with a GBA game, but it's likely that this affects all RetroArch-backed emulators.

### Steps to Reproduce

1. Start a GBA game.
2. Create a save state.
3. Observe that the save state can be recalled.
4. Create 999 more save states.
5. Observe that no save states can be recalled.

### Provide any additional context or information that may help us investigate your issue

Tested using a GBA game.  Likely affects all of RetroArch.

**Comment by Aemiii91** [comment]
This should be directed to: https://github.com/libretro/RetroArch
