### ISSUE TITLE
Select+r2/l2 brightness shortcut conflicts with some games. Disable it for MMP

### ISSUE THREAD

**Issue by light-and-ray** [OnionUI/Onion#892]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

 Onion-v4.2.0-beta-dev-072c73c

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

There is shortcut menu+volume for changing brightness in Plus model. And `select + L2/R2` shortcut may conflicts with control in some ps1 games, and gba/snes games with swaping `R1L1<->R2L2` enabled. For example in _duke nukem advance_ and _gta advance_ `select+L/R` shortcut is used for weapon selection. So it should be disabled for miyoo mini plus

### Steps to Reproduce

Enable r1l2/r2l2 swaping, and then change weapon in duke nukem advance

### Provide any additional context or information that may help us investigate your issue

-

**Comment by Aemiii91** [comment]
This will disabled for MMP in the next release (done in #958)
