### ISSUE TITLE
Wifi option not present in setting

### ISSUE THREAD

**Issue by DanTheDane** [OnionUI/Onion#896]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion-v4.2.0-beta-dev-fa65f9d

### Miyoo Firmware Version

202303292051

### Provide a clear and concise description of the issue

There is no Wifi option present in the Settings menu.

OnionOs has been installed on a freshly formatted (Samsung Evo) MicroSD, and also tried to be reinstalled 3 times (and card reformatted) to no availability.

The Wifi option is present, and working, with the stock os.

### Steps to Reproduce

Install a fresh version of the Onion-v4.2.0-beta-dev-fa65f9d, and go to settings

### Provide any additional context or information that may help us investigate your issue

Installation is done on a Mac, with card formatted using Disk Utility and the format of "MS-DOS (FAT32)

**Comment by Amiga500** [comment]
Confirm same issue with previous beta updated through OTA

**Comment by randyjc** [comment]
Confirmed on my end, after installing on a fresh sdcard from Samsung EVO.
When using stock sdcard I can connect to any wifi network.

**Comment by CurtSweatshirt** [comment]
Comfirmed, I am also using a Samsung EVO.
I did the online updater from the previous beta version to this one and now the wifi settings point is missing, wifi is still working though, but I can not switch network or deactivate it (obviously).

**Comment by z3row0rm** [comment]
Same issue on MM+. Fresh install only keeping only BIOS, ROMS and Saves folders. No WIFI options and in 'About device' Model number is showing MY283 instead of the correct MY354.

**Comment by Aemiii91** [comment]
Fix is on the way ;)

**Comment by k3lt** [comment]
Is this the reason Onion-v4.2.0-beta-dev-072c73c disappeared from https://github.com/OnionUI/Onion/releases ?

**Comment by Aemiii91** [comment]
@k3lt yes.

**Comment by AahilD** [comment]
is there another version of onion I can use for my MM+ while this issue is being resolved?

**Comment by Aemiii91** [comment]
Release available: https://github.com/OnionUI/Onion/releases/tag/latest

**Comment by CurtSweatshirt** [comment]
When will the latest Version come available via online updater?

**Comment by danny-psqr** [comment]
@Aemiii91 Only the source code is available. Is it planned to release the compiled / packaged version?

**Comment by Aemiii91** [comment]
Yes, we had some issues with the installer. I hope to get it fixed tonight (in the next 6 hours)
