### ISSUE TITLE
Ignore dirs starting with a dot in pacman

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#91]
Initial problem : ._ mac files impacts Package Manager -> [see this issue on reddit](https://www.reddit.com/r/MiyooMini/comments/uy3iyv/onionos_installer_showing_dot_files_macos/)

Solution : ignore dirs starting with a dot in pacman

2 objectives : 

  - get ride of automatic creation of files from macs
  - be able to hide / desactivate some cores in pac-man (and we add a little sentence in the wiki, something like : )

> deprecated cores are disabled in pac-man by adding a "." prefix

[Discord conversation about it](https://discord.com/channels/529983248114122762/1007796369785897090/1010130219530719292)

**Comment by schmurtzm** [comment]
> The || should be && !
>  we just need to delete len > 2 ||

**Comment by introkun** [comment]
The issue is not only in PacMan
![image](https://user-images.githubusercontent.com/61635/185705484-de226ab8-081c-411c-aad1-0e8470e340bd.png)
