### ISSUE TITLE
Add mute function to Global Shortcuts

### ISSUE THREAD

**Issue by Taranchul** [OnionUI/Onion#914]
### Checklist

- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and something is incorrect or missing

### Wiki Section

https://github.com/OnionUI/Onion/wiki/Global-Shortcuts

### Description

The mute function by pressing Vol up & down simultaneously is missing from the shortcut page.

### Correction

Add Vol up+down = mute to the shortcuts.

**Comment by duckyb** [comment]
I've added it

![image](https://github.com/OnionUI/Onion/assets/27895007/ad14217b-3b1b-41f8-8bcd-36bf410c34e9)

**Comment by Aemiii91** [comment]
Thanks @duckyb !

**Comment by Taranchul** [comment]
Thanks from me, too!
