### ISSUE TITLE
Apps folders renaming

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#93]
2 possibilities : 

---
**1.**
- [ ] - [ ] To distinguish native apps from third party apps theoretically `PlayActivity`, `ThemeSwitcher`, `Guest_Mode `and `SearchFilter` should be prefixed with `Onion_` .
- [ ] Rename `The_Onion_Installer` into `Onion_Installer` too (To match with `Onion_Manual` , `Onion_Tweaks `)

---
**2.**
- [ ] Or easier : we remove `Onion_` prefix everywhere !

**Comment by Aemiii91** [comment]
If we're renaming them they should just be the same as their labels.

**Comment by Aemiii91** [comment]
The reason for *not* renaming is to have them overwrite old apps on install. And have the old apps still be uninstallable by pacman.

**Comment by Aemiii91** [comment]
`The_Onion_Installer` becomes `PackageManager` !
