### ISSUE TITLE
A problem of sharing Onion system between mini and mini+

### ISSUE THREAD

**Issue by fengfrw** [OnionUI/Onion#946]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion-v4.2.0-beta-dev-41caa40

### Miyoo Firmware Version

miyoo283-fw202306111426 / miyoo354-fw202306092122

### Provide a clear and concise description of the issue

1. The mini adds search (and the location of the theme text setting) under the new firmware, and adds the text "search" character in lang, which causes the corresponding character reference error when sharing the lang file with the mini+ under the miyoo file ("search" is displayed correctly on the mini+, but "WIFI" is displayed on the mini), which needs to be corrected (the official mini and mini+ are separated from the original system, and the relevant lang is independent and has no effect).

2. The shutdown of mini in the system settings of the new firmware(miyoo283-fw202306111426) cannot execute the shutdown command under OnionOS (the shutdown command is normally executed under the official original system).

3. OnionOS can normally display the charging icon and battery power in the upper right corner of mainui on mini+, but the charging icon and battery power cannot be displayed on mainui on mini host (charging icon is normally displayed on some interfaces of OnionOS and official original system).
search
![lang](https://github.com/OnionUI/Onion/assets/99127271/00011f8d-a19d-43da-b52a-19eb1df1134c)

### Steps to Reproduce

Install Onion-v4.2.0-beta-dev-41caa40 on the mini and mini+ host, test the use of the system's own "search" function, execute the shutdown command in the system settings, and observe the icon display on the main interface of charging status.

### Provide any additional context or information that may help us investigate your issue

The same is true with the same TF card on which OnionOS is installed.

**Comment by Aemiii91** [comment]
Possibly fixed in:
- #897
