### ISSUE TITLE
No netplay option from Recent menu

### ISSUE THREAD

**Issue by georgesak** [OnionUI/Onion#950]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0-beta

### Miyoo Firmware Version

202306092122

### Provide a clear and concise description of the issue

From the Recent menu, going in  GLO, no option to start netplay.

### Steps to Reproduce

Enable recent menu
Select game from the menu
Press Y (go in GLO)
No netplay option 

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by XK9274** [comment]
Hey,

Do you mean the new feature (start netplay over hotspot) or are you referring to something else?

**Comment by georgesak** [comment]
Yes, that's what I meant. The wifi direct option (which is awesome btw :).

**Comment by XK9274** [comment]
Hey,

Thanks for the feedback! 

Check the notes/comments on  https://github.com/OnionUI/Onion/pull/891 for a detailed explanation and a temporary solution.

It's something I'm aware of I just need to have a chat with the other guys how best to do it without duplicating too much.

**Comment by georgesak** [comment]
Awesome, thanks!

**Comment by Aemiii91** [comment]
Done in:
- #969
