### ISSUE TITLE
NeoGeo CD cover art not loading

### ISSUE THREAD

**Issue by albixhafa** [OnionUI/Onion#963]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2 beta

### Miyoo Firmware Version

Latest

### Provide a clear and concise description of the issue

The NeoGeo CD emulator does not load cover art pics.  I am using roms i converted from bin to chd and downloaded cover art using skraper. No issues reported with other emulators. 

### Steps to Reproduce

Covert bin(s)to chd 

### Provide any additional context or information that may help us investigate your issue

4.2 beta

**Comment by Aemiii91** [comment]
Need more details, like file system lists / screenshots.
